### ISSUE TITLE
Add documentation to run the server on dev mode

### ISSUE THREAD

**Issue by antho1404** [prismagraphql/prisma#1207]
It is actually quite complicated to run the server locally (in order to work on it to debug or add features)

Once `sbt` installed there is no guideline on the command to start the server (I'm guessing `sbt single-server/run`)

Also it appear that many env variables are missing (even after sourcing the `env_example` file), it looks like the `.envrc` file in the cli is more accurate.

Finally I think it should be nice to have all the dev environment in docker, I had such a pain to install `sbt` on osx with the right java version and still with no luck so finally end up with the following docker command 
```
docker run -it -v `pwd`:/root -p 8081:8000 -p 8082:8080 -p 8083:8083 -p 8084:8084 -p 8085:8085 -p 8086:8086 -p 8087:8087 hseeberger/scala-sbt
```

Even with all that I'm still not able to run the server with no error so I'm probably doing something wrong somewhere that's why a small documentation on this should be great

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @antho1404! With Prisma, the local development workflow should be a lot easier! You can find more info in the new [docs](https://docs-beta.prisma.io/1.13/operate-prisma-server/).
