### ISSUE TITLE
GraphQL API Gateway reference example

### ISSUE THREAD

**Issue by schickling** [prismagraphql/prisma#1314]
As the GraphQL Gateway pattern is emerging as a best practice, we started working a reference example application and new GraphQL tooling to improve development workflows. The overall idea is to **use Graphcool as a GraphQL database** via schema stitching.

The following features will be possible using the GraphQL Gateway:

* Completely customized GraphQL schema
* Wrapping existing (REST) APIs
* Flexible authentication & authorization workflows (will replace static permission system)
* Persisted queries (see #134)
* File upload
* Rate limiting

## Example Application

You can start using this today by forking the following example app: **[graphql-gateway-example](https://github.com/graphcool/graphql-gateway-example)** 🎉

**Comment by James-Firth** [comment]
Perhaps as part of this the current example (with non-working `tar` command it seems?) should be removed as well? (I can make a new issue if that's better)

https://github.com/graphcool/framework/tree/master/examples/node-gateway-custom-schema

**Comment by marktani** [comment]
See https://github.com/prismagraphql/graphql-server-example
