### ISSUE TITLE
Direct database access

### ISSUE THREAD

**Issue by sorenbs** [prismagraphql/prisma#1375]
Prisma is a multi tenant environment that allow you to operate multiple services on a single cluster. An application will typically have access to only a subset of services.

A Prisma Cluster has one or more databases with the following schemas:

- a schema called `prisma` that stores meta data about all services
- a schema for each service on the cluster containing the actual data.

There are two levels of direct database access:

## Service

There should be a simple way to retrieve database credentials for either read access or read/write access to the database schema for a particular service. This should not grant access to the graphcool schema 

## Cluster

There should be a way for cluster administrators to get full access to all schemas.

**Comment by dpetrick** [comment]
For the local docker setup, this involves a minor change in the compose file that maps the database through to an available port on the host machine. People can then set up their GUI tools with the database credentials, or connect to the DB via command line.

For convenience, it is maybe a good idea to print the DB credentials using a command in the CLI.

To get read / write access to the data, the CLI should be able to hand over the appropriate credentials. A self-hosted setup is probably fairly manual in that regard, as secrets have to be managed by the user. However, in a managed cluster, the cloud service should be able to create a database-level user to grant access. This is a more intricate problem to solve in the long run and requires careful planning in the future.

**Comment by veksen** [comment]
@marktani is this still relevant?
