### ISSUE TITLE
The count field in update many and delete many is prone to race conditions

### ISSUE THREAD

**Issue by mavilein** [prismagraphql/prisma#1431]
**Current behavior**
The mutations currently use the provided `where` argument to count the number of nodes that will get affected before actually executing. In the meanwhile data can still change through other concurrent mutations and the count is then outdated.

**Reproduction**
We can only cover this through a unit test imo.

**Expected behavior?**
The count should be not prone to race conditions.

To implement this properly we need bigger refactorings in the backend first.

**Comment by sorenbs** [comment]
I guess what we want is something like `affectedRowsCount ` described in http://slick.lightbend.com/doc/3.0.0/queries.html#deleting

Other than the required refactoring - is there a reason this might not work?
