### ISSUE TITLE
ECONNRESET if `prisma deploy` run too soon after `prisma local nuke`

### ISSUE THREAD

**Issue by schickling** [prismagraphql/prisma#1506]
When running `gc deploy` after running `gc local nuke` the following can happen. This should be handled more gracefully. Either by `gc local nuke` just finishing when the cluster is ready or in the `gc deploy` command.

![image](https://user-images.githubusercontent.com/1567498/34578090-fee55a30-f183-11e7-8304-00f97e63ef6e.png)

**Comment by everdrone** [comment]
experiencing this with prisma `prisma/1.7.1 (darwin-x64) node-v9.5.0`

**steps to reproduce:**
```bash
prisma init
docker-compose up -d
prisma deploy
```

**Comment by marktani** [comment]
This is not valid anymore since the deprecation of the `local` commands.
