### ISSUE TITLE
Rethink local cluster

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#1513]
The local 'cluster' is special in many aspects, compared to remote clusters.

This issue acts as a collection of differences and similarities and provides the basis for a discussion about a separate concept for the local cluster, vs remote clusters.

A couple of thoughts to spark discussion:

* A local cluster is not connected to Prisma Cloud
* The terminology of deploying a service locally might be confusing
* `prisma local` makes the `local` cluster special
* on the other hand, `.prisma/config.yml` treats `local` as just another cluster

**Comment by marktani** [comment]
For local development, a "live reload" feature might be interesting, which could be activated using a `--watch` flag. It would pick up changes to the service configuration and apply them on the fly.

A technical challenge here would be to ensure smooth migrations (also see #1263).

**Comment by pie6k** [comment]
When you have some critical error, it tells you to send request ID to graph.cool support. While it has no sense when request was local, that might be a bit confusing.

**Comment by marktani** [comment]
The local server is not handled specially anymore and is handled the same as any other self-hosted server.
