### ISSUE TITLE
Updating nested types leads to dead data rows.

### ISSUE THREAD

**Issue by pie6k** [prismagraphql/prisma#1516]
Consider such data shape:

```
type Task {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  name: String!
  repeating: Repeating
}

type Repeating {
  maxRepeatsCount: Int
  daysBetweenRepeats: Int
}
```

Now, every time I want to update `repeating info` I run mutation like:

```
mutation {
  updateTask(data: {
    repeating: {
      create: { # I need to use 'create' to update repeating data from task level
        daysBetweenRepeats: 2 # I want to go running every 2nd day instead of every 3rd day
      }
    }
  }, where: {
    id: "cjc21he4q00hv0132jkcg0aym"
  }) {
    id
  }
}

```

Information is updated properly, but old row of data remains there and if I query for 

```
query {
  repeatings {
    daysBetweenTaskSessions
  }
}
```

I'll still have old data sets that are dead now and it's even technically hard-to-impossible to securely delete them if there are a lot of 'similar' rows of data.

Am I doing something wrong (aka is there any better way to manage nested data structures without id based entities)?

Note that I've supplied only little part of my data schape. In reality, nesting is 2-3 levels deep and much more complex leading to many more dead rows on every update

**Comment by marktani** [comment]
Thanks for the report, we'll release a fix in the next beta stage 🙂

**Comment by pie6k** [comment]
Also, as there is no `id` for `Repeating` I think there is no point of using `create` mutation instead of directly setting nested props.

Create is there I bet, to distinguish with `connect`, but there is no way to connect with something without ID.

**Comment by pie6k** [comment]
Any update?

**Comment by do4gr** [comment]
Hey, @pie6k sorry for the late reply. I just looked into it and I can still reproduce the issue. I think the problem is that the API should offer other options in this case. I will try to spec out what the available operations should be for embedded types in the next days. I do not think our current update/delete/upsert mutations can handle embedded types elegantly.
