### ISSUE TITLE
graphql-cli hook should not run when service is already up to date

### ISSUE THREAD

**Issue by kbrandwijk** [prismagraphql/prisma#1523]
```
Service is already up to date.

Hooks:

Writing database schema to `C:\Users\User\Development\github\graphql-boilerplates\node-graphql-server\basic\src\generated\database.graphql` ... 156ms
Running $ graphql prepare...
```

**Comment by marktani** [comment]
There are no automatic hooks anymore, they are manually set up as `hooks` in `prisma.yml`, which is enough for broad use cases.

If you want to adjust the behaviour, or have specific requirements that are currently not met by the hook system, you can set up your own script and invoke it outside of the hook system.

We will consider improving the hook system in the future, to also cover more specific use cases.
