### ISSUE TITLE
Seeding in combination with boilerplate doesn't make sense

### ISSUE THREAD

**Issue by kbrandwijk** [prismagraphql/prisma#1601]
Seeding only works on the initial deployment. Now, if I use a boilerplate, then update my schema and my seed, I cannot seed again, unless I'm deploying to a different stage.

**Comment by kbrandwijk** [comment]
I think it should be possible to have a `graphcool deploy --seed` option, that forces the seed to run on deploy.

**Comment by sorenbs** [comment]
Would `graphcool deploy --seed` reset the data or should we have a separate switch for that?

`graphcool deploy --seed --reset`

See also https://github.com/graphcool/prisma/issues/1536
