### ISSUE TITLE
Log for GraphQL queries in databrowser

### ISSUE THREAD

**Issue by kmelve** [prismagraphql/prisma#161]
It would be useful for beginners and learners to have the possibility to see how edits etc. in the databrowser would look like in GraphQL syntax. Most SQL-based GUIs have this feature (e.g. SequelPro)

**Comment by marktani** [comment]
Issue moved to [prismagraphql/prisma-cloud-feedback #151](https://github.com/prismagraphql/prisma-cloud-feedback/issues/151) via [**ZenHub**](https://www.zenhub.com/)
