### ISSUE TITLE
Change local cluster DB password to 'prisma'

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#1677]
Currently, it's `graphcool`.

**Comment by iamclaytonray** [comment]
This is fixed in #1627

**Comment by dpetrick** [comment]
See https://github.com/graphcool/prisma/pull/1653

**Comment by marktani** [comment]
Should be resolved by https://github.com/prismagraphql/prisma/pull/2254, also the `docker-compose.yml` now directly exposes the `password` field.
