### ISSUE TITLE
`prisma deploy` should ask to start Docker on Mac if not running

### ISSUE THREAD

**Issue by schickling** [prismagraphql/prisma#1697]
`prisma deploy` should display an interactive prompt to either `Start "Docker for Mac"` or `Cancel` if the CLI detected that Docker is installed but not running instead of showing this:

![image](https://user-images.githubusercontent.com/1567498/35184708-60a06c52-fdf9-11e7-858f-67d51d078850.png)

**Comment by supergoat** [comment]
Is somebody working on this? I'm looking to create my first PR (outside of fixing documentation etc)
Is this a good place to start?

**Comment by marktani** [comment]
Hey @supergoat, this is probably not a good first issue (I removed the help wanted flag), feel free to ping me [in Slack](https://slack.graph.cool) (my handle is @nilan) so I can help you find something more suitable 🙂
