### ISSUE TITLE
The Docker Engine you're using is running in swarm mode.

### ISSUE THREAD

**Issue by schickling** [prismagraphql/prisma#1699]
After upgrading to the latest Docker version for Mac and running `prisma deploy`, I'm seeing the following error message (prisma/1.0.4 (darwin-x64) node-v9.4.0):

![image](https://user-images.githubusercontent.com/1567498/35185752-6835419e-fe09-11e7-82bf-efc6533502ff.png)

![image](https://user-images.githubusercontent.com/1567498/35185775-8f47fd26-fe09-11e7-9416-fe53a9011f03.png)

**Comment by marktani** [comment]
This is invalid since the deprecation of the `local` command.
