### ISSUE TITLE
Don't use 3000 as default port

### ISSUE THREAD

**Issue by steida** [prismagraphql/prisma#1714]
Both https://github.com/facebook/create-react-app and https://github.com/zeit/next.js use 3000 as the default port, so I suppose Prisma should choose something else.

**Comment by steida** [comment]
"playground": "graphql playground --port 5000"

**Comment by akoenig** [comment]
Good point! Maybe, we should add this scenario to the FAQ. What do you think @marktani?

**Comment by marktani** [comment]
Hey @akoenig, which FAQ have you thought of? 🙂 
We surely should look into improving the documentation here, thanks for the suggestiojn @steida!

**Comment by akoenig** [comment]
This one over here: https://www.prismagraphql.com/docs/faq/ :)

**Comment by nikolasburk** [comment]
I've added a note to the docs of the `prisma playground` command. Thanks @steida and @akoenig 🙌
