### ISSUE TITLE
prisma init creates config file even if it already exists

### ISSUE THREAD

**Issue by kbrandwijk** [prismagraphql/prisma#1759]
If I have created a `.graphqlconfig.yaml` using `graphql init`, and later run `prisma init`, it will create a `.graphqlconfig.yml`, even though it already exists.

Both cli's have a different default extension for the yml config, and should be unified.

Also, if I create a JSON config file using `graphql init`, `prisma init` still creates a Yaml file.

**Comment by marktani** [comment]
`prisma init` does not create `.graphqlconfig.yml` files anymore.
