### ISSUE TITLE
Connection query example for Relay client

### ISSUE THREAD

**Issue by steida** [prismagraphql/prisma#1769]
Or just a hint. Should I recreate a special type in schema.graphql? I think I am missing something. Thank you.

**Comment by steida** [comment]
Hmm, should I use https://github.com/graphcool/prisma/tree/master/examples/resolver-forwarding?

**Comment by steida** [comment]
Still, I think I am missing something. For example, I need such query on the client.

```
query {
  webs(
    where: {
      owner: {
        id: "cjczcgs62ccml0113szos0gq9"
      }
    },
    orderBy: updatedAt_ASC
  ) {
    name
    owner {
      email
    }
  }
}
```

Is `webs: [Web!]` enough or should I somehow override Web type? Not sure yet what is the recommended practice.

**Comment by marktani** [comment]
You need to use the `xConnection` query, it provides the structure required by Relay. In your case, that would be `websConnection`:

```graphql
query {
  websConnection(
    where: {
      owner: {
        id: "cjczcgs62ccml0113szos0gq9"
      }
    },
    orderBy: updatedAt_ASC
  ) {
    edges {
      node {
        name
        owner {
          email
        }
      }
   }
  }
}
```

**Comment by steida** [comment]
My question was how to project DB websConnection to public API? How schema and resolver should be written?

**Comment by marktani** [comment]
You can use `forwardTo`, similar to here: https://github.com/graphcool/prisma/tree/master/examples/resolver-forwarding

But you would use the `xConnection` query instead 🙂

**Comment by marktani** [comment]
I'm reopening this. An example for relay connections would be super useful!

**Comment by mburak** [comment]
Is forwardTo still valid or is implicit now?
A relay example would be great.
