### ISSUE TITLE
socket hang up when prisma local start on ubuntu server

### ISSUE THREAD

**Issue by johhansantana** [prismagraphql/prisma#1771]
**Current behavior**
When trying to run a local cluster in an ubuntu server and doing `prisma local start` and using `export DEBUG="*"` it stays in a loop with the following logs:

```
  client FetchError: request to http://localhost:4466/cluster failed, reason: socket hang up
  client     at ClientRequest.<anonymous> (/home/johhan_santana/.nvm/versions/node/v8.9.4/lib/node_modules/prisma/node_modules/node-fetch/index.js:133:11)
  client     at emitOne (events.js:116:13)
  client     at ClientRequest.emit (events.js:211:7)
  client     at Socket.socketOnEnd (_http_client.js:423:9)
  client     at emitNone (events.js:111:20)
  client     at Socket.emit (events.js:208:7)
  client     at endReadableNT (_stream_readable.js:1055:12)
  client     at _combinedTickCallback (internal/process/next_tick.js:138:11)
  client     at process._tickDomainCallback (internal/process/next_tick.js:218:9) +214ms
  client requesting http://localhost:4466/cluster +504ms
^C  client FetchError: request to http://localhost:4466/cluster failed, reason: socket hang up
  client     at ClientRequest.<anonymous> (/home/johhan_santana/.nvm/versions/node/v8.9.4/lib/node_modules/prisma/node_modules/node-fetch/index.js:133:11)
  client     at emitOne (events.js:116:13)
  client     at ClientRequest.emit (events.js:211:7)
  client     at Socket.socketOnEnd (_http_client.js:423:9)
  client     at emitNone (events.js:111:20)
  client     at Socket.emit (events.js:208:7)
  client     at endReadableNT (_stream_readable.js:1055:12)
  client     at _combinedTickCallback (internal/process/next_tick.js:138:11)
  client     at process._tickDomainCallback (internal/process/next_tick.js:218:9) +3ms
```

**Reproduction**

1. Create a VPS anywhere with ubuntu 16.04
2. Install docker and docker-compose
3. Install node
4. Install prisma
5. run `prisma local start`
6. It will not run and stay in a loop with `socket hang up`

**Expected behavior?**
Should setup the cluster for deploying with `prisma deploy`

I did a forum question but I think this belongs here:
https://www.graph.cool/forum/t/cant-start-prisma-local-cluster-on-virtual-private-server/2149/3

I've tried many times in different virtual private servers (Vultr, DigitalOcean, Google-Cloud, etc) and always the same result.

I've tried restarting docker, killing all containers, nuking with prisma, upgrading prisma, rebooting the server, updating and upgrading the server with `apt-get update/upgrade`. Nothing seems to work.

```
johhan_santana@prisma:~$ docker -v
Docker version 17.12.0-ce, build c97c6d6
johhan_santana@prisma:~$ docker-compose -v
docker-compose version 1.18.0, build 8dd22a9
johhan_santana@prisma:~$ prisma -v
prisma/1.0.11 (linux-x64) node-v8.9.4
johhan_santana@prisma:~$ node -v
v8.9.4
johhan_santana@prisma:~$ npm -v
5.6.0
```

And sometimes in a macbook it does the same loop in the error but afterwards it completes the execution and the clusters are up and running.

**Comment by harrisrobin** [comment]
@johhansantana  i found that if you run 
`prisma local start` a few times it fixes that issue.

**Comment by johhansantana** [comment]
@harrisrobin I tried doing that a few times, it ends up with errors like:
`ERROR: for local_prisma-database_1 cannot stop container`
and
`ERROR: for prisma-database cannot stop container`

Did `sudo service docker restart` and ran `prisma local start` and ended up with the same `hang up` error.

**Comment by honzavalustik** [comment]
Running into this too. Has anybody figured out how to hot fix it? Repeating ``prisma local start`` not working for me.
