### ISSUE TITLE
Query Complexity / Depth Complexity Validation

### ISSUE THREAD

**Issue by Saeris** [prismagraphql/prisma#1814]
Hey there! This is as much a question as it is a feature request.

Because Prisma uses the SDL instead of `graphql-js` for Type definitions, it's not as easy to reason about how to implement tools such as [`graphql-query-complexity`](https://github.com/ivome/graphql-query-complexity), which adds additional properties to `GraphQLObjectType` fields. Here is an example of what I mean:

```javascript
const Query = new GraphQLObjectType({
  name: 'Query',
  fields: () => ({
    posts: {
      type: new GraphQLList(Post),
      complexity: (args, childComplexity) => childComplexity * args.count, // <- Non-standard property
      args: {
        count: {
          type: GraphQLInt,
          defaultValue: 10
        }
      }
    },
  }),
});
```

Additional properties like this can be used elsewhere in the application, in this case in the `validationRules` of an Apollo server, or as I've used them in my projects, for dynamically generating Input objects, enums, etc (examples here: [Type Definition](https://github.com/Saeris/Scribe/blob/develop/src/types/artist.js) [`createFilter` function](https://github.com/Saeris/Scribe/blob/develop/src/utilities/createFilter.js) [`createInput` function](https://github.com/Saeris/Scribe/blob/develop/src/utilities/createInput.js) [`createOrder` function](https://github.com/Saeris/Scribe/blob/develop/src/utilities/createOrder.js), also see [`join-monster`](https://github.com/stems/join-monster)).

So the question here is how would I go about implementing something like this in Prisma? I asked @schickling this recently at a meetup and this issue is the follow up to that.

But at the end of the day, a concrete example of why you might want to do this in the first place is to implement query validation rules as in the first example, which is where a feature request comes in: Can we get complexity validation added to Prisma?

I'm looking for a system which can perform static analysis on an incoming query to evaluate it's cost before executing it. This would help to prevent overloading the server with deeply nested queries or executing a ton of costly resolvers (examples could include deferred network requests such as forwarding to third-party REST endpoints or calling device APIs). Basically it's better to fail fast, and this helps do that.

Here's another great article explaining the how's an why's behind all this for reference:
https://www.howtographql.com/advanced/4-security/

Perhaps this can be exposed in the SDL through some new directives? I could see that working in-part, in that I could assign a `cost` score to individual fields, which can then be used by a validation function to compare an incoming query to a cost threshold defined in the server's config somewhere.

Depth complexity should be easier to implement, as it should just be a validation rule that doesn't rely on additional properties. Though I'm not sure how to implement this in Prisma either. Here's a library I use with my Apollo servers for this: https://github.com/stems/graphql-depth-limit

I'll leave it off here to open things up for discussion. Would like to hear other people's thoughts on similar use-cases making the switch from `graphql-js` to using the SDL.

**Comment by sorenbs** [comment]
Thanks for opening this conversation Drake!

First, it is important to clearly define the terms in use:

`Prisma` is a Data Access Layer - it turns your database into a GraphQL API.
`graphql-bindings` makes it easy to implement resolvers in your GraphQL server by delegating to Prisma. Read about the general concept in https://blog.graph.cool/reusing-composing-graphql-apis-with-graphql-bindings-80a4aa37cff5

There is no fundamental reason you shouldn't be able to use `graphql-query-complexity` with `graphql-binding` in your GraphQL API when using Prisma. If this is currently not possible then we should work on fixing the issue.

Going further, I think there is an opportunity for Prisma to provide more accurate cost analysis. Prisma has very direct information about performance of the underlying database. In the future we will be smarter about using this information to optimise queries, and we could also surface this information back to the GraphQL app layer. This is a bit further out in the future though.

**Comment by Saeris** [comment]
Yeah, sorry for the confusion here. My understanding of the project has changed a bit from a conversation I had after writing this. I originally felt this was a good place to file the issue because I used the examples from this repo to get started using Prisma myself.

I'll take a look through the blog post you linked at see if I can't find a solution there.

It would be really nice to have more performance information to use in cost analysis. This issue is definitely something that's an important consideration in a production environment, but isn't necessary to get up and running.

**Comment by heymartinadams** [comment]
Slightly related: @Saeris, have you been able to use [graphql-depth-limit](https://github.com/stems/graphql-depth-limit) in conjunction with Prisma / graphql-yoga?

I don’t see where [GraphQLServer](https://github.com/prismagraphql/graphql-yoga#graphqlserver) has a place to insert validation rules, such as what’s needed for [graphql-depth-limit](https://github.com/stems/graphql-depth-limit).
