### ISSUE TITLE
From time to time not regenerated schema on new Float field

### ISSUE THREAD

**Issue by Fi1osof** [prismagraphql/prisma#1821]
# Bug Report

When i add new field type Float such test5: Float and do prisma deploy, table updated, but schema not regenerated. 
Log:
```
$ prisma deploy
Deploying service `com` to stage `dev` on cluster `local` 43ms

Changes:

  User (Type)
  + Created field `test5` of type `Float`

Applying changes 1.0s

Your GraphQL database endpoint is live:

  HTTP:  http://localhost:4466/gglobal_com/dev
  WS:    ws://localhost:4466/gglobal_com/dev


Hooks:
Checking, if schema file changed 240ms
```

There no Writing database schema to `src/generated/prisma.graphql`

**Comment by marktani** [comment]
Hey @Fi1osof, could this be the same problem as described here: #2193?

**Comment by Fi1osof** [comment]
I'm not sure.
But solution for me: delete src/generated/prisma.graphql and run prisma deploy again.
