### ISSUE TITLE
Add filters for enum lists

### ISSUE THREAD

**Issue by oxy88** [prismagraphql/prisma#1858]
Prisma 1.1.3

Here's my model
```
type User {
  id: ID! @unique
  favoriteCities: [City!]!
  city: City
  favoriteNumbers: [Int!]!
  number: Int
  favoriteidioms: [String!]!
  idiom: String
}

enum City {
  NewYork,
  London,
  Madrid,
}
```

Here's the WhereInput
```
input UserWhereInput {
  AND: [UserWhereInput!]
  OR: [UserWhereInput!]
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  city: City
  city_not: City
  city_in: [City!]
  city_not_in: [City!]
  number: Int
  number_not: Int
  number_in: [Int!]
  number_not_in: [Int!]
  number_lt: Int
  number_lte: Int
  number_gt: Int
  number_gte: Int
  idiom: String
  idiom_not: String
  idiom_in: [String!]
  idiom_not_in: [String!]
  idiom_lt: String
  idiom_lte: String
  idiom_gt: String
  idiom_gte: String
  idiom_contains: String
  idiom_not_contains: String
  idiom_starts_with: String
  idiom_not_starts_with: String
  idiom_ends_with: String
  idiom_not_ends_with: String
}
```

I can't find users whose favorite cities are NewYork and London or favorite numbers are 1,7,8

**Comment by marktani** [comment]
Hey @oxy88, thanks for reporting this!

> favorite cities 

Are you sure about this? Please double check that you deployed, and reloaded the schema afterwards.   `UserWhereInput` should include `favoriteCities_none`, `favoriteCities_some` and `favoriteCities_every`.

> favorite numbers

This is expected. We'll add filters for scalar lists soon, according to [this specification](https://github.com/graphcool/prisma/issues/1275).

**Comment by oxy88** [comment]
@marktani 
Thank you for reply.
I sure there is not enum type filter in generated schema.
https://github.com/oxy88/enumtype
prisma 1.3.5

**Comment by marktani** [comment]
Thanks @oxy88, I can confirm that enum lists don't yet have a filter. 
Earlier I misread the City enum as a type in your schema, sorry about that!

**Comment by marktani** [comment]
This is further continued in #1275.
