### ISSUE TITLE
.env file should not contain "" 

### ISSUE THREAD

**Issue by steida** [prismagraphql/prisma#1868]
Maybe I am wrong, but tools like https://github.com/motdotla/dotenv or https://github.com/toddbluhm/env-cmd expect 

```
# This is a comment
ENV1=THANKS
ENV2=FOR ALL
ENV3=THE FISH
```

... environment values without strings. Prisma generates examples with FOO="VALUE".

**Comment by marktani** [comment]
You can also use double quotes 🙂 
Here's an example: https://github.com/motdotla/dotenv/blob/master/examples/basic/.env

**Comment by steida** [comment]
But https://github.com/este/este/commit/845784cd22ce1fe44a95c7f857a6d37feb05a1a0
I spend hours trying to figure out why I have wring values then I realized both plugins injected values with quotes ![screen shot 2018-02-10 at 19 57 17](https://user-images.githubusercontent.com/66249/36065545-9ffd37a0-0e9c-11e8-8237-58f3f738ed0c.png)

**Comment by steida** [comment]
Exactly this ![screen shot 2018-02-10 at 19 54 37](https://user-images.githubusercontent.com/66249/36065548-b8532dfa-0e9c-11e8-961e-35876e51650e.png)

**Comment by steida** [comment]
@marktani It can have double quotes, but then I would have to remove them in babel plugins somehow.

**Comment by tfiwm** [comment]
No i think the standard is without and i had the same problem with docker. I recommend to remove them.

My usecase was to create a docker image of my api server and there for i put the environment information directly if i start a container of my image:

```
docker run --name visual-knight-test -t --env-file .env-test -p 127.0.0.1:4000:4000 visual-knight/visual-knight-api
```

Docker is taking the double quotes as value. Is it a problem to remove the double quotes? dotenv can handle it without.

**Comment by steida** [comment]
@schickling This another PITA. Super confusing for debugging. Please.

**Comment by schickling** [comment]
Thanks for your thoughts @steida. @timsuchanek could you take a look into this and explore this further with @steida?

**Comment by steida** [comment]
It's easy. Several tools will not remove passed quotes so as result things don't work.

**Comment by nikolasburk** [comment]
@steida I assume you were referring to the generation of the advanced boilerplates which have been removed from the `prisma init` command. Therefore I'm closing this issue. Please reopen the issue if that was not correct.
