### ISSUE TITLE
Logout command for Prisma CLI

### ISSUE THREAD

**Issue by divyenduz** [prismagraphql/prisma#1870]
# Feature Request

**What feature are you missing?**
We can add a command (`prisma logout`) to log out from Prisma CLI. 

**How could this feature look like in detail? Tradeoffs?**
We can programmatically remove the `cloudSessionKey` from `~/.prisma/config.yml` and document this in `prisma help`. 

Related issue: https://github.com/graphcool/prisma/issues/1861

I can take this up, please let me know.

**Comment by timsuchanek** [comment]
Thanks for raising this issue @divyenduz! That approach totally makes sense!
Feel free to start implementing it, you have the go from my side!
If you have any further questions, you know where to reach me ;)

**Comment by jeremyscatigna** [comment]
Hey ! I can help you on that if needed ! Let me know how I can help 🚀

**Comment by marktani** [comment]
This is now available at `1.13-beta`.
