### ISSUE TITLE
Clearly communicate the different use cases for Prisma

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#1891]
In some cases, it's a great idea to directly connect to the Prisma endpoint from the frontend.
In other cases, operating a GraphQL Server for handling business logic is the preferred option.

There are some sections about in the docs already, but this needs be explained better.

**Comment by nikolasburk** [comment]
This is covered [here](https://docs-beta.prisma.io/1.13/understand-prisma/prisma-introduction-what-why-how-j9ff/#how-does-prisma-fit-into-your-stack)
