### ISSUE TITLE
Relay add mutation

### ISSUE THREAD

**Issue by steida** [prismagraphql/prisma#1949]
Must return something with edge and cursor probably. Graphcool had it implemented somehow. What should the recommended implementation for Prisma look like? Thank you.

**Comment by steida** [comment]
I somehow managed it https://github.com/este/este/blob/760d490a3ef4e7501c9381387a6dcb9ca6aa2646/server/resolvers/index.js#L106

But I don't know what cursor should be and also, I mysteriously have the same problem as here https://github.com/facebook/relay/issues/1744

**Comment by marktani** [comment]
Hey @steida, thanks for bringing this up. Can you share your current progress, and any open questions?

We should look into the general experience with Relay. @nikolasburk could you think about that one? 🙂

**Comment by virtualirfan** [comment]
@nikolasburk re: @marktani's comment about looking into general relay experience.

fwiw: Relay experience is currently a pretty difficult, if not non-existent :-(
* There are no examples to follow. HowToGraphQL [relay examples](https://www.howtographql.com/react-relay/2-queries-loading-links/) are outdated and don't use latest generated APIs.
* #1780 is a blocker and I can't figure out how to manually insert the inner edges with a GraphQL Server
