### ISSUE TITLE
Nested Mutation: `updatedAt` not updated

### ISSUE THREAD

**Issue by akoenig** [prismagraphql/prisma#1996]
# Bug Report

**Current behavior**

When I perform a nested update mutation in which I connect and create other related objects, the `updatedAt` of the actual object on which the  mutation has been executed won't enjoy a change.

```graphql
return context.db.mutation.updateConversation(
    {
      where: { id: conversation.id },
      data: {
        messages: {
          create: {
            author: {
              connect: {
                id: context.user.id
              }
            },
            text: args.input.text
          }
        }
      }
    },
    info
  );
```

In fact that makes sense, because although I execute `updateConversation` I don't change anything in the actual object. My assumption was that even then the `updatedAt` of `Conversation` will be updated. As you can see: From a technical point this can be explained. From the assumption of using just the API, ehm, it is hard to grasp 😄 

**Reproduction**

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

**Expected behavior?**

That `updatedAt` will be updated to the current date in a nested mutation, even when no change on the actual object happens.

**Comment by marktani** [comment]
This is not a bug, but intended behaviour.

Personally, I prefer the current behaviour, but I can see why your suggested behaviour is useful, too.

Note that you can accomplish what you want by adding a `dummy` field and updating it to any value:

```ts
return context.db.mutation.updateConversation(
    {
      where: { id: conversation.id },
      data: {
        dummy: 'touch',
        messages: {
          create: {
            author: {
              connect: {
                id: context.user.id
              }
            },
            text: args.input.text
          }
        }
      }
    },
    info
  );
```

I'd be interested to hear more opinions about this topic.

**Comment by etx** [comment]
Could I use this dummy value to update with the generated api? I'm sending back all the variables from my form but if none of them change, the only change was on a related field, I do not see the updatedAt field updated. I assume prisma is seeing the values are all equal to their current values and considering the data to not be updated.

**Comment by marktani** [comment]
Correct.
