### ISSUE TITLE
(Circle) CI + Prisma

### ISSUE THREAD

**Issue by KATT** [prismagraphql/prisma#2000]
# Bug Report

_⚠️ Not sure this is a bug, might be my issue, but I got asked on Slack to post this here. ⚠️_

## Current behavior

Unable to create local Prisma cluster with Circle CI.

When running `prisma local start` Circle CI gets stuck at _Booting local development cluster..._ until it eventually times out.

### Output

```
#!/bin/bash -eo pipefail
cd api
yarn prisma local start
yarn prisma deploy
yarn run v1.3.2
$ /home/circleci/repo/api/node_modules/.bin/prisma local start

Booting local development cluster...Too long with no output (exceeded 10m0s)
```

- [**Example setup**](https://github.com/KATT/react-prisma-graphql-shopping-cart/blob/39092a7723355bbc346f747d134fdc42781babe5/.circleci/config.yml#L47-L51)
- [**Example Output**](https://circleci.com/gh/KATT/react-prisma-graphql-shopping-cart/341)

## Reproduction

1. Fork https://github.com/KATT/react-prisma-graphql-shopping-cart
1. Login to [Circle CI](https://circleci.com)
1. Setup your fork in Circle CI
1. Will rebuild whenever you push

## Expected behavior?

`yarn prisma deploy` to work

## Notes

I don't have to do this with Circle CI - if someone has working examples with Travis/Jenkins/.. I'd be happy to switch.

**Comment by marktani** [comment]
Thanks so much for bringing this up @KATT! We're looking into this and will provide more resources here soon 🙂

**Comment by KATT** [comment]
Went with Travis instead. Was hassle-free. Implementation here: https://github.com/KATT/shop/pull/3

**Comment by andrewjmead** [comment]
I'm seeing the same behavior with `prisma local start`. It never finishes. 

Prisma version: 1.8.3
Docker version: 18.03.1
Node version: 10.1.0

**Comment by KATT** [comment]
Related: #2437

**Comment by divyenduz** [comment]
@KATT - I was able to get this to working by using [machine executor](https://circleci.com/docs/2.0/executor-types/) in Circle CI. The docker executor in Circle CI has a remote docker container not available on the network. 

[Config file used](https://github.com/divyenduz/ds/blob/18e57f3b2270b5c7952f00ce2cb1ffabecb19d20/.circleci/config.yml)

[Passing build with Prisma deploy](https://circleci.com/gh/divyenduz/ds/64) 

Can you please follow [this example](https://github.com/divyenduz/ds) and raise a PR in [Prisma examples](https://github.com/prismagraphql/prisma/tree/master/examples)?

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue. I'm closing it since we now have a [travis example](https://github.com/prismagraphql/prisma/tree/master/examples/travis).
