### ISSUE TITLE
Changes to only directives are not recognized

### ISSUE THREAD

**Issue by iamclaytonray** [prismagraphql/prisma#2001]
# Bug Report

**Current behavior**
When making changes to `datamodel.graphql`, Prisma CLI seems to cache the previous results for several minutes when trying to deploy those changes. Caching may not be the correct term but that's what it best represents in my mind.

**Reproduction**

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

I don't really have time to build a demo repro but will try sometime this week. Essentially, all I am doing is upgrading my old `graphcool` project data model. For example, change `defaultValue(value: "")` to `default(value: "")`. The CLI will continue to give the error to change to `default(value: "")`.

It seems as if only directives are affected by this caching. I have not noticed this effect elsewhere. Will update should that happen.

**Expected behavior?**
Anytime changes are made, the CLI should be accept those changes to deploy immediately instead of resolving within a few minutes

**Comment by marktani** [comment]
This sounds like changes to _only_ directives aren't correctly picked up.
Have you managed to reproduce this when _also_ changing the data model itself?

**Comment by iamclaytonray** [comment]
Yeah, I guess I should have mentioned that. Thanks for the catch @marktani

**Comment by marktani** [comment]
Thanks, I updated the title accordingly.

**Comment by iamclaytonray** [comment]
I think this can be closed. I haven't had this issue in a while.
