### ISSUE TITLE
Using variables in prisma.yml from command line options doesn't work

### ISSUE THREAD

**Issue by nikolasburk** [prismagraphql/prisma#2004]
For **bug reports**, please fill out the [bug report issue template](https://github.com/graphcool/prisma/issues/new?template=bug.md)

It should be possible to set variables in `prisma.yml` via command line options, as documented [here](https://www.prismagraphql.com/docs/reference/service-configuration/prisma.yml/using-variables-nu5oith4da#cli-options).

Consider this `prisma.yml`:

```yml
service: eroing
stage: ${opt:stage}

datamodel: datamodel.graphql

disableAuth: true
```

Now, passing a `stage` option fails as follows:

```
~/D/myapp $ prisma deploy --stage dev
 ▸    [WARNING] in .../myapp/prisma.yml: A valid option to satisfy the declaration 'opt:stage' could not be found.

 ▸    Invalid prisma.yml file
 ▸    prisma.yml should have required property 'stage'. missingProperty: stage

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
```

Right now, the CLI always fails with the following error: 

```
 ▸    [WARNING] .../myapp/prisma.yml: A valid option to satisfy the declaration 'opt:stage' could not be found.
```

**Comment by marktani** [comment]
We decided to remove this feature. We should

* update the documentation
* remove all remaining code
