### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by wolszczak96** [prismagraphql/prisma#2035]
Hi!

I want to make a point about contributing guides. There is a nice general [contributing.md](https://github.com/graphcool/prisma/blob/master/CONTRIBUTING.md) file, but further instructions are very poor. Server [contributing.md](https://github.com/graphcool/prisma/blob/master/server/CONTRIBUTING.md) is even empty. It would be nice to complete guidelines to make it easier for the community to contribute.

**Comment by akoenig** [comment]
@wolszczak96 Valid points. Do you have something in mind you think is especially hard / hindrance?
