### ISSUE TITLE
Description of environment variables of prismagraphql/prisma image in Docker Hub

### ISSUE THREAD

**Issue by Artemidas** [prismagraphql/prisma#2054]
In the documentation there is no clear explanation around environment variables. The good place to describe them would be Docker Hub.

In some examples you have:
```
SQL_CLIENT_HOST=prisma-db
SQL_CLIENT_PORT=3306
SQL_CLIENT_USER=root
SQL_CLIENT_PASSWORD=__SECRET_2__
SQL_CLIENT_CONNECTION_LIMIT=10

SQL_INTERNAL_HOST=prisma-db
SQL_INTERNAL_PORT=3306
SQL_INTERNAL_USER=root
SQL_INTERNAL_PASSWORD=__SECRET_2__
SQL_INTERNAL_DATABASE=graphcool
SQL_INTERNAL_CONNECTION_LIMIT=10
```
It is not clear (for me) where points each set of variables.

**Comment by Aubron** [comment]
Also, can't help but feel that some of them are relics of the former framework service, and not something something would need in a self deployment. I have a kubernetes deployment on GKE, but it was... painful.

**Comment by CloudGrimm** [comment]
I am failing to set up the environment variables for my API to as to recognise the prisma service, how best can the services be set on GKE to allow my API to communicate with the prisma server? @Aubron @marktani

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @Artemidas! The environment variables you're mentioning are now part of the `PRISMA_CONFIG` env var which is extensively documented in the new [docs](https://docs-beta.prisma.io/). Therefore I'm closing this issue! 🙏
