### ISSUE TITLE
Accessing deployed database without token is confusing

### ISSUE THREAD

**Issue by FredyC** [prismagraphql/prisma#2066]
# Feature Request

**What feature are you missing?**

When following Quick start guide I've deliberately chosen template "typescript + auth" instead of recommended "basic" as I knew I am going to need both of those. Unfortunately, the guide did not account for that so after everything is started and I've navigated to `http://docker:4466/prisma/dev` _(I love there is the playground right away)_ there was no clear evidence of any issue except in Schema tab there was no schema so I could not run any queries.

At this point, I wasn't really sure what's wrong and if I've misunderstood some part of the setup. Only later trying to open the dev console and after refresh seeing it's missing a token. And once again I wasn't really sure where to get one until I asked on the Slack that I need to run `prisma token`.

It's kinda funny now seeing that if I would have followed to the last point of the quick start guide, I would have started `yarn dev` and everything would be working right away without messing with a token.

**How could this feature look like in detail? Tradeoffs?**

The guide cannot probably account for impatient people like me. I was too excited and wanted to see it's working and then giving up seeing it's not. Perhaps the actual mention of the url where database is running is misleading there. 

However, the playground should definitely provide more feedback on errors during initial schema introspection instead of just silently sitting there. I am not sure about add there hint about using `prisma token` since it's more of a generic software.

**Comment by nikolasburk** [comment]
Thanks a lot for the feedback @FredyC and (again) sorry for the delay! I'm closing this issue as we have restructured our entire quickstart experience in the meantime.
