### ISSUE TITLE
SQL_INTERNAL_DATABASE not used to bootstrap new prisma server 

### ISSUE THREAD

**Issue by piscis** [prismagraphql/prisma#2082]
# Bug Report

**Current behavior**
When I deploy primsa (v1.3.5) via docker-compose and set the environment SQL_INTERNAL_DATABASE to something else then graphcool this will not be picked up by the prisma bootstrapping process for a new not.

```
:Query is: CREATE SCHEMA IF NOT EXISTS `graphcool` DEFAULT CHARACTER SET latin1;[1]:	
at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)[1]:	
at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)[1]:	
at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)[1]:
... 24 more[1]:Listening for transport dt_socket at address: 8000
```
**Reproduction**

1. Deploy a new cluster via docker-compose.yml (fresh mysql instance + prisma)
2. Set the SQL_INTERNAL_DATABASE to something else than graphcool
3. Deploy the config via docker compose.
4. whatch the logs to see if the database will be bootstrap

**Expected behavior?**
It should take the environment variable SQL_INTERNAL_DATABASE via environment variable to initial create a schema for prisma.

**Comment by piscis** [comment]
I think others had this problem as well https://github.com/graphcool/prisma/issues/1972#issuecomment-368317976

**Comment by piscis** [comment]
Could this be the problem?

https://github.com/graphcool/prisma/blob/c77e582b5fd6edc62d18bb03d060f5f2d3d2172a/server/connectors/deploy-connector-mysql/src/main/scala/com/prisma/deploy/connector/mysql/database/InternalDatabaseSchema.scala#L15-L18

**Comment by do4gr** [comment]
A fix for this is available in stable now.

**Comment by do4gr** [comment]
You are using an outdated version of the Prisma server config. We have an outstanding issue to properly document the new config format here https://github.com/prismagraphql/prisma/issues/2508
