### ISSUE TITLE
Prisma endpoint for subscriptions breaking on refresh or stop/start on graphql playground

### ISSUE THREAD

**Issue by georgelovegrove** [prismagraphql/prisma#2094]
When using graphql playground on a prisma endpoint the subscription will only work on first usage. On refreshing the page or stop/starting the subscription it will break.

When using a front facing server that consumes the same endpoint you can stop/start and refresh graphql playground subscriptions and this works fine.

Original forum post:
https://www.graph.cool/forum/t/prisma-endpoint-subscriptions-only-working-once-with-tokens-on-graphql-playground/2833

**Comment by marktani** [comment]
Hey @georgelovegrove, could you try again with the latest versions of `graphql-yoga`, `prisma-binding` and GraphQL Playground? 🙂

Also, if this issue persists, could you please explain what exactly is the behaviour you observe? Do you get an error message, or something else?

Thanks! 🙌
