### ISSUE TITLE
Digital Ocean (Docker Machine) docs misleading.

### ISSUE THREAD

**Issue by christophertrudel** [prismagraphql/prisma#2099]
# Bug Report

**Current behavior**
```
Listening for transport dt_socket at address: 8000
Exception in thread "main" com.typesafe.config.ConfigException$UnresolvedSubstitution: application.conf @ jar:file:/app/lib/com.prisma.prisma-local-0.8.0-0ec094028cb8d8b95fcdbb834bb229f75079f048.jar!/application.conf: 54: Could not resolve substitution to a value: ${SCHEMA_MANAGER_SECRET}
```

**Reproduction**
https://github.com/graphcool/prisma/blob/master/docs/1.4/03-Tutorials/04-Cluster-Deployment/01-Digital-Ocean-(Docker-Machine).md
The current docs have `SCHEMA_MANAGER_SECRET` and `SCHEMA_MANAGER_ENDPOINT` in the `.env` however the `docker-compose.yml` doesn't make use of it. After I stuck them in I had success.

**Expected behavior?**
I believe this might have been missed. Not sure how many docs might have the same issue.

**Comment by marktani** [comment]
Thanks a lot for reporting this, @christophertrudel! What do you mean with stucking them in? 🙂

**Comment by christophertrudel** [comment]
Sorry for not explaining that in more detail. 
[01-Digital-Ocean-(Docker-Machine).md](https://github.com/graphcool/prisma/blob/master/docs/1.4/03-Tutorials/04-Cluster-Deployment/01-Digital-Ocean-(Docker-Machine).md) setup caused me issue with this error
```
Listening for transport dt_socket at address: 8000
Exception in thread "main" com.typesafe.config.ConfigException$UnresolvedSubstitution: application.conf @ jar:file:/app/lib/com.prisma.prisma-local-0.8.0-0ec094028cb8d8b95fcdbb834bb229f75079f048.jar!/application.conf: 54: Could not resolve substitution to a value: ${SCHEMA_MANAGER_SECRET}
```
`Could not resolve substitution to a value: ${SCHEMA_MANAGER_SECRET}` lead me to search for it's uses in the codebase. I discovered that `SCHEMA_MANAGER_SECRET`  is found in `.env` of every **Digital-Ocean-(Docker-Machine)** tutorial from _V1.0 - V1.4_ but missing from the `docker-compose.yml` from _V1.1 - V1.4_.

So I tried adding
```
SCHEMA_MANAGER_SECRET: $SCHEMA_MANAGER_SECRET
SCHEMA_MANAGER_ENDPOINT: $SCHEMA_MANAGER_ENDPOINT
```
to `docker-compose.yml`  just like was done in [02-Digital-Ocean-(Docker-Machine).md](https://github.com/graphcool/prisma/blob/master/docs/1.0/03-Tutorials/04-Cluster-Deployment/02-Digital-Ocean-(Docker-Machine).md) and the error went away and the cluster started working.

Not sure if this was a mistake removing them from the docs or it was intended and somehow by adding created a crazy fix to something else. I would suspect that the values were removed by mistake.

I quickly added a [PR](https://github.com/graphcool/prisma/pull/2100) to resolve if that is in fact the issue.

**Comment by smcelhinney** [comment]
Can confirm I also ran into this issue, and @christophertrudel 's fix worked for me too.

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @christophertrudel and apologies for the delay 🙏 As `SCHEMA_MANAGER_SECRET ` and `SCHEMA_MANAGER_ENDPOINT ` are not part of the Prisma server config any more, I'm closing this issue.
