### ISSUE TITLE
Renaming service contributes to initial confusion

### ISSUE THREAD

**Issue by FredyC** [prismagraphql/prisma#2104]
# Feature Request

**What feature are you missing?**

After bootstrapping with `prisma init` and some initial fiddling, I have renamed service in `prisma.yml` file, did some changes to database schema and deployed. When I wanted to use changes from within the server app, it was giving errors that do not really make sense. Only later I have discovered that there is a wrong `PRISMA_ENDPOINT` using old outdated service.

**Possible solutions for smoother experience**

* When running `prisma init`, ask for service name right away so it can be a correct right off the bat. Obviously, this does not solve further renaming issues later.
* Include `PRISMA_SERVICE` in the `.env` so it's next to the `PRISMA_ENDPOINT` and it's easier to spot this needs to be updated as well.
* Alternatively to previous solution instead of having whole endpoint there, have only `PRISMA_HOST` variable and assemble endpoint dynamically at runtime. That would be most error prone solution in my opinion.

**Comment by nikolasburk** [comment]
Hey @FredyC, we changed how the `prisma init` command works. It sounds like you were referring to the creation of a GraphQL boilerplate which now has been moved to the [GraphQL CLI](https://github.com/graphql-cli/graphql-cli). Therefore I'm closing this issue!

Still, thanks a lot for opening this issue! Please keep on opening issues if you run into any problems in the future!
