### ISSUE TITLE
Explain stable and unstable release channels in docs

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2107]
Prisma releases are separated into two channels - the stable and unstable channel.

The unstable channel is released with every commit to master and therefore gives access to features and bug fixes before the stable release.

We close issues when the fix or feature is available on the unstable channel.

The release channels and related dynamics should be explained in the Prisma documentation.

Existing resources:

* https://github.com/graphcool/prisma/blob/master/README.md#contributing
* https://github.com/graphcool/prisma/blob/master/CONTRIBUTING.md#the-unstable-channel
* https://github.com/graphcool/prisma/wiki/Release-Channels

**Comment by nikolasburk** [comment]
This is documented [here](https://docs-beta.prisma.io/1.13/operate-prisma-server/channels-and-releases-oje2/#using-the-alpha-and-beta-channels)
