### ISSUE TITLE
Broken schema

### ISSUE THREAD

**Issue by terion-name** [prismagraphql/prisma#2148]
Fighting with programmatic control (#1948) I've already handled to bring it all up, but suddenly I've began to face a strange issue on server's schema introspection:

```
{ Syntax Error: Expected Name, found }

GraphQL request (2:1)
1: type Mutation {
2: }
   ^
3: interface Node {

    at syntaxError (/usr/src/app/node_modules/graphql/error/syntaxError.js:24:10)
    at expect (/usr/src/app/node_modules/graphql/language/parser.js:1299:32)
    at parseName (/usr/src/app/node_modules/graphql/language/parser.js:92:15)
    at parseFieldDefinition (/usr/src/app/node_modules/graphql/language/parser.js:809:14)
    at many (/usr/src/app/node_modules/graphql/language/parser.js:1348:16)
    at parseFieldsDefinition (/usr/src/app/node_modules/graphql/language/parser.js:799:50)
    at parseObjectTypeDefinition (/usr/src/app/node_modules/graphql/language/parser.js:757:16)
    at parseTypeSystemDefinition (/usr/src/app/node_modules/graphql/language/parser.js:663:16)
    at parseDefinition (/usr/src/app/node_modules/graphql/language/parser.js:143:16)
    at parseDocument (/usr/src/app/node_modules/graphql/language/parser.js:110:22)
  message: 'Syntax Error: Expected Name, found }',
  locations: [ { line: 2, column: 1 } ],
  path: undefined }
```

As it can be seen from db, project was succesfully deployed and migrated (with db schemas provided by `graphql-server-example`):

<img width="1792" alt="2018-03-23 20 24 26" src="https://user-images.githubusercontent.com/1060205/37847332-2f593730-2ed9-11e8-9fbd-9cb0f7b2ea75.png">

<img width="1792" alt="2018-03-23 20 24 41" src="https://user-images.githubusercontent.com/1060205/37847417-7226d37e-2ed9-11e8-8864-34ab9c65abfc.png">

Also the project db is present and all tables seem to be ok.

But schema is broken:

<img width="1311" alt="2018-03-23 20 26 13" src="https://user-images.githubusercontent.com/1060205/37847446-87f0a31a-2ed9-11e8-89a1-dace5a54c4a5.png">

<img width="411" alt="2018-03-23 20 26 31" src="https://user-images.githubusercontent.com/1060205/37847456-8e700db6-2ed9-11e8-9bc5-93f69e13a222.png">

And this is happening on all 1.3, 1.4 and 1.5-beta

**Comment by terion-name** [comment]
This is insane. Keeping EVERYTHING the same, except application name:

test-dosvit-app-prisma-mysql — not working
test-dosvit-app-mysql-prisma — not working
test-dosvit-appmysql-prisma — WORKING
test-dosvit-app_mysql_prisma — working

How this could even be?

**Comment by marktani** [comment]
Do you notice problems for the following two? 

* `abc-abc-abc-abc-abc`
* `abc-abc-abc_abc_abc`

**Comment by terion-name** [comment]
@marktani  I'm digging this all and as for now it seems to be not naming, but a very strange networking (?) problem. I noticed that everything breaks when I am connecting to the docker network another container with graphql-express, that consumes (proxying) prisma via internal network and binds/exposes port 3000. Will update when dig out more details

**Comment by terion-name** [comment]
@marktani I've finally got it. The situation is like this:

I bring up a mysql container, a prisma container and a separate application container.

The process:

1. Start mysql and wait it to be ready
2. Start Prisma and wait it to be ready
3. Read the configs and db-graphql-shemas
4. Create the project in Prisma and migrate it
5. Start application container

The application container contains an app that on start gets Prisma CRUD schema from server, generates bindings and starts Prisma db instance:
```js
const crudSchema = await introspectSchema(new HttpLink({uri: prismaEndpoint, fetch}));
// by some reason prisma inputs are printed with strange triple-quoted comment blocks, so we remove them
const cleanCrudSchema = printSchema(crudSchema).replace(/"""[^"]+"""/g, '').replace(/^\s*[\r\n]/gm, '');
const prismaBindings = bindingsGenerator(cleanCrudSchema, 'prisma-js');
const Prisma = requireFromString(prismaBindings).Prisma;
const db = new Prisma({
  endpoint: prismaEndpoint,
  secret: 'secret', // just to be, servers are passwordless
  debug: true,
});
```

And now the tricky part: if application container starts and tries to run `introspectSchema`  **too early** (can't figure out the minimum timings yet) — Prisma server breaks as described in issue. 

If I add a timeout for app container to start:
```js
const bridge = await docker.container.create(require('../configs/bridge').config(manifest.name, networkName, ['mysql']));
await network.connect({Container: bridge.id});

sleep.msleep(5000); // <==== timeout

await bridge.start();
```
then everything works correctly.
