### ISSUE TITLE
Fullstack React boilerplate docs refer to database/seed.graphql which does not exist

### ISSUE THREAD

**Issue by merges** [prismagraphql/prisma#2158]
Docs: https://www.prismagraphql.com/docs/quickstart/fullstack/react/apollo-tijghei9go
Contains broken link to: https://github.com/graphql-boilerplates/react-fullstack-graphql/tree/master/basic/server/database/seed.graphql

`seed.graphql` is also not created when running `prisma init`.

**Comment by nikolasburk** [comment]
Hey @merges, seems like the link https://github.com/graphql-boilerplates/react-fullstack-graphql/tree/master/basic/server/database/seed.graphql is actually valid. Please let us know if you run into any further issues :)
