### ISSUE TITLE
Old .import folder is not cleaned up correctly

### ISSUE THREAD

**Issue by printedheart** [prismagraphql/prisma#2165]
# Bug Report

**Current behavior**
Old DataSetAExport
New DataSetBExport

`.import` folder can be left behind when importing different exports

**Reproduction**

After importing DataSetAExport and failing or timing out or repeating on `prisma import -d DataSetAExport.zip` a folder named `.import` can be left in the directory.

The data is reset with `prisma reset`

When then attempting to import DataSetBExport `prisma import -d DataSetBExport.zip` a series of errors on Relations or Nodes listed below:

`   "Failure inserting into relationtable _AssetProductFeaturedphoto with ids cja4a<id>si3 and cja4b<id>cl. Cause: java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`<cluster>-prisma@env`.`_AssetProductFeaturedphoto`, CONSTRAINT `_AssetProductFeaturedphoto_ibfk_1` FOREIGN KEY (`A`) REFERENCES `Asset` (`id`) ON DELETE CASCADE)"
]`
or
`  "Failure inserting into relationtable _AssetProductFeaturedphoto with ids cja4a42pl53ch01550gkf2si3 and cja4bmby764qk0144eoc5itcl. Cause: java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`vyrl-prisma@pink`.`_AssetProductFeaturedphoto`, CONSTRAINT `_AssetProductFeaturedphoto_ibfk_1` FOREIGN KEY (`A`) REFERENCES `Asset` (`id`) ON DELETE CASCADE)"
]`

This can be resolved by:

`rm -rf .import`
`prisma reset`
`prisma import -d DataSetBExport.zip`

**Expected behavior?**
prisma import should perform something similar to yarn build where it checks and cleans up .import
`rimraf .import && tsc -u 1 .import/`

**Comment by steve-a-jones** [comment]
Having this exact same issue.. oddly services created a month+ ago work fine for me.. newly created services are now throwing `SQLIntegrityConstraintViolationException` and importing data minus relations.. Would love to see this get some attention as `prisma import` is fairly hard to trust in our CI pipeline ATM (after import we do an export and diff to ensure import actually succeeded)

**Comment by divyenduz** [comment]
Fixed via https://github.com/prismagraphql/prisma/pull/2625 which is currently in beta. I can confirm that this also fixes the seeding issue as mentioned by @marktani

**Comment by divyenduz** [comment]
This is fixed in CLI version 1.10.1. Please use `npm install -g prisma` to update 🎉
