### ISSUE TITLE
"The server was not able to produce a timely response to your request" when importing data

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2185]
This error message can occur when importing data into a Prisma service.

This means that importing a _chunk_ of data took more than the timeout limit - currently it is set to 300s.

The [NDF](https://www.prisma.io/docs/reference/data-import-and-export/normalized-data-format-teroo5uxih) for data export/import separates data (nodes, relations, lists) into _chunks_. The recommended chunk size is 1MB, to prevent the timeout issue. However, different causes can cause a chunk to be bigger than 1MB:

* Exporting data from Graphcool Framework using `graphcool export` used a chunk size of 10MB before - [see related PR](https://github.com/graphcool/graphcool-framework/pull/501). If this applies to your export, you can either split the chunks into smaller parts manually, or export the data again.

* A node cannot be spread across multiple chunks - so when a node is bigger than 1MB, it will fill up a whole chunk. This chunk will be as big as the node itself. If this applies to your export, your import should still go through most of the time. If that's not the case, you can think about stripping columns with large content, and import them in a separate step.

1MB is a rather conservative size. Even though your chunks might end up being larger than that, that doesn't automatically lead to a timeout.

Please let me know in a comment below if you encounter this error message and are not able to circumvent it with the above instructions 🙂

**Comment by aboglioli** [comment]
I was testing it. This problem seems to occur on slow hard drives. If you are using a SSD disk, you can import data without errors. I think it's a speed problem.
