### ISSUE TITLE
Json variables are not validated

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2210]
# Bug Report

**Current behavior**

Json is not correctly validated.

**Reproduction**

```graphql
type MyRequiredJson {
  id: ID! @unique
  json: Json!
}
```

replace `__ENDPOINT__`:

```sh
curl '__ENDPOINT__' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: https://eu1.prisma.sh' -H 'json: {}' --data-binary '{"query":"mutation b($json: Json!) {\n  createMyRequiredJson(data: {json: $json}) {\n    id\n  }\n}", "variables": {"json": " "}}' --compressed
```

This sets the `json` value to `" "`, which is invalid.

**Expected behavior?**

An error is thrown, saying that `" "` is not a valid value for `Json`.

**Comment by marktani** [comment]
I put the variables in the HTTP headers instead the variables field. 💡

**Comment by SHASHANK-PRO-05** [comment]
@marktani I wanted to contribute to this issue. Can you inform me about the location where to look into the code?

**Comment by marktani** [comment]
Hey @SHASHANK-PRO-05, I suggest to set up a failing test case as the first step, then you can step through the code to see the entire code path that is executed 🙂 

You can add a new `JsonVariablesSpec` file. Just create a new file and add a new test case similar to [this spec](https://github.com/prismagraphql/prisma/blob/master/server/servers/api/src/test/scala/com/prisma/api/queries/SingleItemQuerySpec.scala).

You can use the `query` method and its `variables` parameter for the Json variable test case. Here is [the function](https://github.com/prismagraphql/prisma/blob/master/server/servers/api/src/test/scala/com/prisma/api/ApiTestServer.scala#L28).

**Comment by do4gr** [comment]
This fix is available in stable now.
