### ISSUE TITLE
Duplicate relations when connect many-to-many self relations and disconnect relation problem

### ISSUE THREAD

**Issue by kieusonlam** [prismagraphql/prisma#2213]
# Bug Report

prisma 1.6.0
prisma-us1

**Current behavior**

My English is quite bad, so I don't know if I describe it good enough to understand.

Database schema
```graphql
type Post {
  id: ID! @unique
  title: String!
  related: [Post!]! @relation(name: "RelatedPosts")
}
```

Connect 3 record will duplicate relation, and you cannot disconnect all relation by updating one of them.

A connect B & C, we will get A + B & C

B connect C & A, we will get B + C & A & A (I use the same query to connect relation on the front-end so it's duplicated the record A which is already connected)

If we just connect B to C everything is work normally. But when we connect the record already connected with an another, it will cause problems.

**Now disconnect**

As the above result we have B + C & A & A

Update B disconnect A, we will get B+ C & A

Update B disconnect A again, we will get error eventhough the relation is still exist.

And we cannot disconnect relation by update A for all record. We have to try to update every single item from A B C to disconnect all the record.

**Reproduction**

### Query all current Posts

```graphql
{
  posts {
    title
    related {
      title
    }
  }
}
```
the result
```graphql
{
  "data": {
    "posts": [
      {
        "title": "A",
        "related": []
      },
      {
        "title": "B",
        "related": []
      },
      {
        "title": "C",
        "related": []
      }
    ]
  }
}
```

### Connect A to B & C
```graphql
mutation {
  updatePost (
    title: "A"
    data: {
      related: {
        connect: [{
          title: "B"
        },
        {
          title: "C"
        }]
      }
    }
  ) {
    title
    related {
      title
    }
  }
}
```
result
```graphql
{
  "data": {
    "updatePost": {
      "title": "A",
      "related": [
        {
          "title": "B"
        },
        {
          "title": "C"
        }
      ]
    }
  }
}
```
### Connect B to C & A
```graphql
mutation {
  updatePost (
    title: "B"
    data: {
      related: {
        connect: [{
          id: "C"
        },
        {
          id: "A"
        }]
      }
    }
  ) {
    title
    related {
      title
    }
  }
}
```
result
```graphql
{
  "data": {
    "updatePost": {
      "title": "B",
      "related": [
        {
          "title": "A"
        },
        {
          "title": "C"
        },
        {
          "title": "A"
        }
      ]
    }
  }
}
```
the relation A is duplicated and when you try to disconnect all relation from 3 of them (A, B, C) there will be an error.

When disconnect B & A the 2nd times we will get

> "The relation RelatedMovies has no node for the model Post with the value 'B' for the field 'title' connected to a node for the model Post with the value 'A' for the field 'title'"

**Expected behavior?**

It's should not duplicate the records, and disconnect should work the right way.

**P/S:** If there is a way to force connect all relation (like old graphcool framework), I think it might work easier and we will have less problem. I mean 

If we have A connected to B & C

We use the query to connect A to B & D it auto drop all relations and connect again the result is

A connected to B & D 

This way might less problems and we don't need to disconnect A and C.

**Comment by do4gr** [comment]
Hey, thanks for reporting this. I think I know what is going on there. Just to be sure is your schema something like this? So without a backrelation on post?

```graphql
type Post{
   id: ID! @unique
   title: String! @unique
   related: [Post!]!
}
```

**Comment by kieusonlam** [comment]
Hi @do4gr 

Yes, It's look almost the same:
```graphql
type Post{
   id: ID! @unique
   title: String!
   related: [Post!]!
}
```

**Comment by kieusonlam** [comment]
Thanks, I can wait for it. I don't think it good if we use too many field because what if we have more 3 relations.

**Comment by do4gr** [comment]
I think we have fixed this in the latest `1.12-beta`. It would be great if you could verify this!

**Comment by kieusonlam** [comment]
Thanks. I'm going to give it a try.

I quest it is this PR https://github.com/prismagraphql/prisma/pull/2515 right? So we don't back relation after connect a relation?

**Comment by do4gr** [comment]
Yes, that is the PR that changed the behavior.
