### ISSUE TITLE
Unable to use null properties in queries and mutations with TypeScript

### ISSUE THREAD

**Issue by mctep** [prismagraphql/prisma#2235]
# Bug Report

**Current behavior**

It is impossible to mutate to `null` or to query by `null` values in TypeScript.

**Reproduction**

```gql
// datamodel.graphql
type Record {
  field: String
}
```

```ts
ctx.db.query.records({
  where: {
    field: null // Compile Error [ts]  Type 'null' is not assignable to type 'string | undefined'.
  }
});

ctx.db.mutation.updateRecord({
  data: {
    field: null // Compile Error [ts]  Type 'null' is not assignable to type 'string | undefined'.
  }
})
```

**Expected behavior?**

`Input` types should use nullable values for optional fields.

**Comment by FredyC** [comment]
Yea, just run into this. Typescript bindings are incorrectly generated for non-required fields. I believe that issue is on this line where it doesn't include `| null` in case on nullable field.

https://github.com/graphql-binding/graphql-static-binding/blob/8ddd494704ee224850e6c825c4ea5da1bb464814/src/generators/graphcool-ts.ts#L262

**Comment by divyenduz** [comment]
Thanks for reporting this one. This is resolved in `prisma-binding` 2.0. Please refer to the [migration guide](https://www.prisma.io/docs/reference/prisma-bindings/code-generation-cosha9rah3#upgrading-from-prisma-binding-v1.x).

**Comment by FrankSandqvist** [comment]
Is prisma-binding 2.0 supposed to make update inputs that are have union types with the type and null?

I updated to 2, but it still just makes them optional (instead of nullable)

**Comment by marktani** [comment]
In terms of GraphQL, nullable and optional is the same thing.
Are you talking about the TS types? If so, please bring this up in a new issue over at https://github.com/prismagraphql/prisma-binding 🙂 

Commenting in closed issues is discouraged as it is easily lost in the sea of GitHub notifications. New issues are easier to keep in mind.

**Comment by FrankSandqvist** [comment]
Ah, thanks for replying. I made a topic in the forum further describing my problem. Cheers
