### ISSUE TITLE
Invalid Typescript typing for Json type

### ISSUE THREAD

**Issue by obibring** [prismagraphql/prisma#2239]
# Bug Report

`prisma-binding` generates the `Json` typescript typing as: 
```typescript
/*
Raw JSON value
*/
export type Json = string
``` 
However, the following fails:
```js
ctx.db.mutation.updateUser({
  myJsonProperty: JSON.stringify({ hello: 'world' })
});
```
While this succeeds:
```js
ctx.db.mutation.updateUser({
  myJsonProperty: { hello: 'world' }
});
```

**Current behavior**
```json
"prisma-binding": "^1.5.17",
"prisma": "^1.6.3",
```
Prisma DB throws an error when attempting to stringify Json fields.

**Expected behavior?**
Either the `Json` typescript typing needs to be changed, or the functionality needs to change to accept a stringified object.

**Comment by nickluger** [comment]
Exactly. Our code is filled with `as any` assertions because of that. I think some versions before, **stringified** JSON was accepted, later that changed to plain objects which are then stringified by Prisma binding?

**Comment by divyenduz** [comment]
I am able to replicate this with `prisma-binding` 2.0 as well.
