### ISSUE TITLE
Payment example with Stripe

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2241]
It would be great to see a fullstack Stripe example with Prisma. 🙂

**Comment by KATT** [comment]
I have a full-stack "e-commerce example" over at [github.com/KATT/shop](https://github.com/KATT/shop)... would fit very nicely as part of that, but I have little time to do it.

**Comment by kitten** [comment]
@marktani I was thinking of writing a Medium article. Maybe I could copy the end result over into the examples here?

I've used Stripe + Prisma for the Dank Mono site, which has been an absolute delight :heart:

**Comment by marktani** [comment]
Thanks so much everyone, really love that we can share our experience together 🙌

@jangerhofer I think we can keep it simple for the start and cover the most common workflows. Register a user, process an order, ... things like that. 

@kitten that would be amazing 🙌 Let me know if you are looking for feedback for your article 🙂

**Comment by KATT** [comment]
(@kitten I like your GH username. "KATT" means "cat" in Swedish 😽)
