### ISSUE TITLE
Add --env-file parameter to "prisma seed"

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2269]
# Feature Request

**What feature are you missing?**

Currently, `prisma seed` does not support the `--env-file` parameter. This means it only works with hardcoded values in `prisma.yml`, or with `.env`, but not with `.env.my.test`.

**How could this feature look like in detail? Tradeoffs?**

```
prisma seed # take `.env`
prisma seed --env-file .env.my.test # take another file
```

**Comment by LawJolla** [comment]
`prisma seed` is a non starter for me without this.

I run, for instance:

```
prisma reset -e .env.test
prisma import -e .env.test -d ./database/seed/basic_server
```
