### ISSUE TITLE
"Syntax Error: Expected Name, found }" for graphql prepare with project setup

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2287]
# Bug Report

**Current behavior**

**Reproduction**

```sh
git clone https://github.com/OGNeutron/Prisma_main_hub.git syntax-error
cd syntax-error
git checkout 0acf304b61c35d3658967e8a965b70e693f2bf6b
prisma deploy
prisma deploy
```

results in this output:

```sh
Deploying service `default` to stage `default` to server `local` 66ms
Service is already up to date.

post-deploy:
Running echo "Deployment finished" ✔
"Deployment finished"

Running graphql get-schema --project db ✔

Running graphql prepare !
 ▸    Syntax Error: Expected Name, found }
 ▸

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ set -x DEBUG "*"
```

`graphql prepare` results in this output:

```sh
✖ Generating bindings for project db...
Syntax Error: Expected Name, found }
```

![image](https://user-images.githubusercontent.com/1780597/39303541-d65cafc0-4956-11e8-9327-d21b3e25b060.png)

**Note:** I tried to deploy the datamodel in a fresh project, with the same `.graphqlconfig.yml` setup. I couldn'y reproduce the error then. 

**Expected behavior?**

No syntax error is returned.

**Comment by OGNeutron** [comment]
I've finally got it working, but I had to start from scratch, I must have made a weird error somewhere, though still wondering how to generate a prisma.graphql from the database one.

I hope there's a boiler plate setup in the future, I can show mine if anyone wants it, it's relatively quick, not as a quick as previously done, but just run prisma init, than graphql init and just deploy, only thing I need to work out which I stated already is the code generation, like previously with generated/schema.graphql I am only getting the prisma.ts

**Comment by Huvik** [comment]
I experienced same stuff today, I had to delete generated schema and bindings.

**Comment by Huvik** [comment]
This datamodel worked: 
```
type PersonImages {
  title: String
  left: File @relation(name: "LeftImage")
  right: File @relation(name: "RightImage")
}
```
when removing `title` i got this error on prepare

**Comment by divyenduz** [comment]
The checkout step in reproduction fails for me
```
divyendusingh [syntax-error]$ git checkout 0acf304b61c35d3658967e8a965b70e693f2bf6b
fatal: reference is not a tree: 0acf304b61c35d3658967e8a965b70e693f2bf6b
```

Unable to reproduce otherwise but I noticed that path to datamodel.graphql in `prisma.yml` was wrong.

**Comment by divyenduz** [comment]
Related issue that I was able to reproduce: https://github.com/graphql-cli/graphql-cli/issues/319

**Comment by marktani** [comment]
Closing as duplicate of #2623
