### ISSUE TITLE
Prisma delete requires authentication to Prisma cloud

### ISSUE THREAD

**Issue by kriswep** [prismagraphql/prisma#2303]
# Bug Report

**Current behavior**
When executing the `prisma delete` command, while not being logged in to Prisma cloud, the CLI opens a browser window to login to cloud. This is for a deployment to the Prisma eu sandbox env.
That behaviour is espescially problematic in a CI env.

This is on prisma 1.7.3 versions. Also checked on primsa 1.8.0, problem still exists.

**Reproduction**
You can start with a new prisma app , e.g. the node basic boilerplate.
- `graphql create my-app --boilerplate node-basic`
- Make sure you're not logged in to prisma cloud, check in `~/.prisma/config.yml`
- Run `npm run prisma delete -f` in the new project folder
- A browser window for log in to Prisma cloud is opened

**Expected behavior?**
Not being required to be authenticated to cloud for the sandbox environment. Older version (1.7.1) did not have this behaviour

```
prisma "version"

prisma/1.7.3 (linux-x64) node-v8.9.0
```

**Comment by kriswep** [comment]
Just checked back on `prisma@1.8.0` and the problem regarding `prisma delete` is still unreolved.

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
