### ISSUE TITLE
Document docker/docker-compose workflows for deprecated local commands

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2312]
* `prisma local nuke`, see #2302
* `prisma local start`
* `prisma local stop`
* `prisma local upgrade`

This should be put into the ref docs, and mentioned from the release notes + upgrade guide.

**Comment by nikolasburk** [comment]
Is this not covered [here](https://www.prisma.io/docs/reference/prisma-servers-and-dbs/prisma-servers/docker-aira9zama5)?

**Comment by marktani** [comment]
Currently, there is no easy way to see what exact `docker`/`docker-compose` commands I can use to end up with exactly the same behaviour as the old `prisma local` commands.

I had something in mind like this:

> To nuke your Docker containers run this:
> ```sh
> docker-compose kill
> docker-compose down
> docker-compose up -d
> ```

**Comment by nikolasburk** [comment]
Do you think this is still needed in the new docs @marktani? Note that we have this page: https://docs-beta.prisma.io/1.13/operate-prisma-server/deployment-environments/docker-rty1

I understand you want a mapping from the `local` commands to `docker  compose`, I'm actually not sure that's needed?! If so it should probably be part of the  upgrade guide here: https://docs-beta.prisma.io/1.13/maintain/upgrade-prisma/upgrade-to-1.7-jgpt#deprecating-local-commands

**Comment by marktani** [comment]
I think those new docs are great! Will report back with specific commands if I stumble across them 🙂
