### ISSUE TITLE
Prisma 1.7.4 delete broken

### ISSUE THREAD

**Issue by georgelovegrove** [prismagraphql/prisma#2325]
**Current behavior**

When creating a new project with prisma 1.7.4 globally installed the delete functionality does not work correctly.

**Reproduction**

npm install -g prisma
prisma init test-prisma
prisma deploy
prisma delete

<img width="442" alt="screen shot 2018-05-03 at 14 49 20" src="https://user-images.githubusercontent.com/6073296/39565394-f89930a0-4ee1-11e8-8e83-dc428ebda23f.png">
Image shows error when trying to prisma delete a deployed prisma server. You can delete the app manually on the app.prisma.sh

**Comment by marktani** [comment]
![image](https://user-images.githubusercontent.com/1780597/39566658-9edd5796-4ebc-11e8-9118-2f92d2e178f1.png)

I can confirm that this happens when deploying to the Prisma development server. Somehow, the stage `dev` is taken instead of the workspace.

**Comment by frandiox** [comment]
Same issue when updating to 1.7.4 and trying the new `prisma seed --reset`. The only apparent solution is removing the service manually in Prisma Cloud dashboard.

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
