### ISSUE TITLE
sbt build error 

### ISSUE THREAD

**Issue by ArvinGanesan** [prismagraphql/prisma#2349]
While trying build prisma, I got the following error : 
[error] java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class coursier/shaded/fastparse/core/LowestPriSequencer. Method $anonfun$Sequencer1$1(Ljava/lang/Object;Ljava/lang/Object;)Lscala/Tuple2; at index 39 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef

[sbt build error.txt](https://github.com/graphcool/prisma/files/1975380/sbt.build.error.txt)

**Comment by mavilein** [comment]
Hey,

this is an error within sbt that can occur from time to time. I have a shell function to fix this issue:
```
fixSbt () {
	find . -regex ".*/target" -exec rm -r {} +
}
```
Just run this command within the project root and it will recursively clean all target folders.
