### ISSUE TITLE
"prisma deploy -n" does not migrate pre 1.7.x prisma.yml file

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2354]
# Bug Report

**Current behavior**

Running `prisma deploy -n` with an existing `prisma.yml` file does not convert `service`, `stage` and `cluster` correctly.

Here is what happens:

* line 19 in the screenshot is added
* nothing happens to line 1-3
* no backup file is created

![image 11](https://user-images.githubusercontent.com/1780597/39663085-f0664e0e-506c-11e8-863f-58f55f6f460f.png)

**Expected behavior?**

* backup file with old values should be created
* line 19 should be added in new file
* line 1-3 should be removed in new file

**Comment by marktani** [comment]
`prisma deploy -n` currently comments out the `endpoint` property and appends the new endpoint in the now commented out line, which should be adjusted as well.

**Comment by divyenduz** [comment]
```
divyendusingh [prisma-2354]$ cat prisma.yml
#endpoint: http://localhost:4466
#endpoint: http://localhost:4466/z/z
endpoint: https://eu1.prisma.sh/divyenduz/prisma-2354/dev
datamodel: datamodel.graphqldivyendusingh [prisma-2354]$ prisma --version
prisma/1.10.2 (darwin-x64) node-v10.4.0
```

Unable to replicate with Prisma CLI `1.10.2`. 
Appends the endpoint in newline correctly.

**Comment by marktani** [comment]
The original issue is invalid. Persisted the other one here: https://github.com/prismagraphql/prisma/issues/2742.
