### ISSUE TITLE
Can't deploy services with names starting with a digit

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2379]
# Bug Report

**Current Behaviour**

![image](https://user-images.githubusercontent.com/1780597/39766375-6d148794-52e4-11e8-8487-7fd22debabdb.png)

```yml
endpoint: https://my-server_my-workspace.prisma.sh/1-8-beta/dev
datamodel: datamodel.graphql
```

**Expected Behaviour**

* either it works
* or the error message contains the information that a service name needs to start with a letter

**Comment by marktani** [comment]
This is still an issue.

**Comment by marktani** [comment]
this is the current error message, which is helpful and accurate:
```ERROR: 1test is not a valid name for a service name. It must start with a letter and may contain up to 30 letters, numbers,
 underscores and hyphens.```

**Comment by vctormb** [comment]
> This is the current error message, which is helpful and accurate:
> 
> ```
> ERROR: 1test is not a valid name for a service name. It must start with a letter and may contain up to 30 letters, numbers,
>  underscores and hyphens.
> ```

I'm having this issue too! No idea how to proceed.

**Comment by marktani** [comment]
Change your service name so that it adheres to the naming convention.

**Comment by vctormb** [comment]
@marktani I already did that. I've tried different names but nothing works.
