### ISSUE TITLE
Postgres introspection of pluralised column names results in pluralised types and double pluralised relations [1.8 ]

### ISSUE THREAD

**Issue by stefl** [prismagraphql/prisma#2386]
When generating a schema from a Ruby on Rails project's Postgres database, the types and relations have unexpected and grammatically incorrect pluralisation.

**Current behavior**

A Postgres database where tables are named in plural format: 'users', 'subscriptions' and so on, results in a schema where the Prisma types are also pluralised. 

In addition, relations to other tables are double pluralised: a 'users' has many 'subscriptionss'.

The database I tried to generate a schema for is one that sits behind a Ruby on Rails application, where this pluralised naming convention is standard.

**Reproduction**

Create a Postgres database with a 'users' table and a 'subscriptions' table using the `psql` commandline:

    CREATE DATABASE prisma_test;
    \c prisma_test
    CREATE TABLE users (id bigserial primary key, username text);
    CREATE TABLE posts (id bigserial primary key, title text, user_id bigint);
    ALTER TABLE posts ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id);

Exit `psql` and then run `prisma init`.

The resulting schema:

    type Posts @pgTable(name: "posts") {
      id: Int!
      title: String
      user: Users @pgRelation(column: "user_id")
    }
    
    type Users @pgTable(name: "users") {
      id: Int!
      username: String
      postss: [Posts!]!
    }

**Expected behavior?**

I would expect that the types be singular: 'User' and 'Post' and that the relation between users and posts be called 'posts'.

Furthermore, and I'll open a separate discussion about this, the introspection-based schema generator only generates the `posts` relation if the database has foreign keys set up, rather than offering up 'posts' as a relation given that there is a 'user_id' column on the 'posts' table.

**Comment by bpb27** [comment]
This is still an issue. I have a Postgres "accounts" table, which results in this:

![image](https://user-images.githubusercontent.com/6701060/49946448-04f15900-febd-11e8-8684-8f4bfa476dbd.png)

Since all the tables in my DB follow that same pattern, all the queries are off, and I can't really adopt Prisma if everything has glaring spelling / pluralization mistakes.

Any thoughts on what to do?

**Comment by scalhoun** [comment]
Same issue here, any way to manually override behavior?
