### ISSUE TITLE
"Workspace dev does not exist" when deleting service from demo server

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2390]
# Bug Report

**Current behavior**

When being logged in and running `prisma delete` with a service that is deployed to the demo server, you receive this response:

```json
ERROR: Workspace dev does not exist

{
  "data": {
    "generateClusterToken": null
  },
  "errors": [
    {
      "message": "Workspace dev does not exist",
      "locations": [
        {
          "line": 3,
          "column": 9
        }
      ],
      "path": [
        "generateClusterToken"
      ],
      "code": 222
    }
  ],
  "status": 200
}

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ set -x DEBUG "*"
```

**Reproduction**

Use this `prisma.yml` and run `prisma delete` while being logged in

```
endpoint: https://eu1.prisma.sh/public-starscowl-123/workspace-dev-not-found/dev
datamodel: datamodel.graphql
```

**Expected behavior?**

The service is deleted.

**Comment by nhuesmann** [comment]
Glad to see this submitted, I've been losing my mind trying to delete a demo service I deployed! I ran into this issue after starting a project using the [node-graphql-server-advanced](https://github.com/graphql-boilerplates/node-graphql-server/tree/master/advanced) boilerplate.

**Comment by vsimko** [comment]
Same problem here.
As a workaround you can still delete the services through the ["prisma console" online](https://app.prisma.io).

**Comment by divyenduz** [comment]
Unable to replicate this with `prisma` cli 1.9. Tried the following:-

1. Demo server with `public-` name.
1. Demo server with workspace under my username.
1. Node advanced boilerplate as suggested in a comment.

Please comment / reopen if this persists for you but do remember to update to 1.9+ via `npm install -g prisma`.

Thanks!
