### ISSUE TITLE
Specified schema in cli not picked up

### ISSUE THREAD

**Issue by wieseljonas** [prismagraphql/prisma#2407]
After trying to introspect an existing database with more than one schema it doesn't pick the correct one.

Issue is probably coming from the this line:

https://github.com/graphcool/prisma/blob/04c783ccb3b75aaf9357889785e93827df1a8ea4/cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts#L277

**Comment by marktani** [comment]
I think this is a duplicate of #2402, but at least related.

**Comment by divyenduz** [comment]
Fixed in alpha via https://github.com/prismagraphql/prisma/pull/2559

**Comment by wieseljonas** [comment]
This step is indeed fixed. Created a new issue because now I cannot connect to the right schema
