### ISSUE TITLE
Better documentation for Relay support

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2427]
* there are `posts` queries (akin to Simple API) and `postsConnection` queries (akin to Relay API)
* there is no `viewer` query - you can build it in your GraphQL Server if needed

Might be a good example as well! 🙂

Also, relevant feature request is #1780 (can be hooked up in GraphQL Server manually already)

**Comment by virtualirfan** [comment]
Any suggestions on how to manually hook this up in a GraphQL Server manually?
