### ISSUE TITLE
Subscriptions are not working

### ISSUE THREAD

**Issue by TheMrugraj** [prismagraphql/prisma#2432]
Subscriptions that we wrote as well as default ones are not working.  When we try to subscribe one of them via Graphql Playground its showing error like below:

```
{
  "error": "Could not connect to WebSocket endpoint ws://my/url/to/prisma/APP/server. Please check if the endpoint url is correct."
}
```

The same thing is happening with Auto Generated Subscriptions
```
{
  "error": "Could not connect to websocket endpoint ws://my/url/to/prisma/graphql/DATABASE/server. Please check if the endpoint url is correct."
}
```

I also tried script([https://gist.github.com/marktani/5df524523693c88be425bfb623ca8b8a](https://gist.github.com/marktani/5df524523693c88be425bfb623ca8b8a)) using plain HTML WebSockets that shows below error in the console
`WebSocket connection to 'ws://my/url/to/prisma/graphql/db/server' failed: Error during WebSocket handshake: Unexpected response code: 200
`

**Comment by TheMrugraj** [comment]
1. We have set up the server as explained in [this blog](https://blog.graph.cool/how-to-deploy-a-prisma-cluster-to-aws-fargate-using-docker-cloudformation-293aa8727b89) which is running on AWS Fargate.

2. Yes, we tried to deploy a fresh and minimal project but the same issue is there with it.

3. Earlier we were on v1.7.3, and now we have upgraded to v1.8.3.

**Comment by marktani** [comment]
2. Can you share that minimal setup, so we can start looking into the problem? 🙂Ideally as a Github repository with steps for the reproduction.

**Comment by marktani** [comment]
The error messages makes me believe it's a network error or similar, so the more you can share about your specific setup, the easier it is to learn more about this problem 🙂

I am not able to reproduce this locally.

**Comment by TheMrugraj** [comment]
I understand that 😊 

But, This issue got resolved today after downgrading and then again upgrading to newer version of Prisma binding. However, we were on the same version before so, it's strange but yeah its working now 😄 

Thanks a lot for your support @marktani

**Comment by marktani** [comment]
I see, great that you figured this one out! I can imagine that there are some unexpected interactions if some dependencies don't match up, but can't say for sure sure :slightly_smiling_face:

**Comment by KumarAbhirup** [comment]
i have the same problem 👎

**Comment by Fabiomad85** [comment]
Same problem here

**Comment by meodemsao** [comment]
i have the same problem
