### ISSUE TITLE
Relation with no back-reference failing on deploy

### ISSUE THREAD

**Issue by mburak** [prismagraphql/prisma#2438]
**Current behavior**
When using an @relation with a name, and no back-reference, it still fails with the error "A relation directive with a name must appear exactly 2 times." 

**Reproduction**
```
type Transaction {
  ...
  buy_amount: Float
  buy_currency: Currency @relation(name: "BuyCurrency")
  sell_amount: Float
  sell_currency: Currency @relation(name: "SellCurrency")
}

type Currency {
  id: ID! @unique
  name: String!
  symbol: String!
}
```

**Expected behavior?**
Back-references are supposed to be optional.

**Comment by marktani** [comment]
Hey @mburak, this is currently expected if there are at least 2 relations to the same outgoing type - `Currency` in this example. A feature request to allow this situation exists here: #1907.
