### ISSUE TITLE
Querying root `node` returns an incorrect type name

### ISSUE THREAD

**Issue by kgoggin** [prismagraphql/prisma#2455]
**Current behavior**
When querying against the root `node` type, the `__typename` of the result is different from the actual type of the node. I'm also unable to query type-specific fields of `node` by creating a fragment for a specific type - I get no results.

**Reproduction**
I copied over my SDL to a new project and reproduced the error there as well.

 * GraphQLBin link to show incorrect queries: https://graphqlbin.com/v2/Xo6Esn
 * Repo with SDL : https://github.com/kgoggin/prisma-node-bug

Also worth noting I initially encountered the error while working with a local PostgreSQL DB, so it doesn't seem tied to local vs. remote or MySQL vs. Postgres.

**Expected behavior?**
Querying the `node` with an Id should return the associated node with the correct type name. Should be able to query `node` with inline fragments for expected type and get a result.

**Comment by do4gr** [comment]
Thanks reporting this. I can reproduce it and am looking into this

**Comment by do4gr** [comment]
The fix is available in stable now.
