### ISSUE TITLE
".grpahqlconfig" file is not aviable in the provided config directory....

### ISSUE THREAD

**Issue by guog** [prismagraphql/prisma#2461]
# Bug Report

**Current behavior**

In the [prism docs 1.8 `TUTORIALS > Setup Prisma > Create New DB`](https://www.prisma.io/docs/tutorials/setup-prisma/create-new-db/mysql-gui4peul2u/), follow the step-by-step instructions in the tutorial.

When you go to [Step 6: Explore Prisma's GraphQL API in a GraphQL Playground](https://www.prisma.io/docs/tutorials/setup-prisma/create-new-db/mysql-gui4peul2u/#step-6:-explore-prismas-graphql-api-in-a-graphql-playground), 

After you execute `prisma playground` ,  an error message pops up at the  GraphQL Playground.

The error message is as follows:
```
".grpahqlconfig" file is not aviable in the provided config directory....
```

Can't explore Prisma API in GraphQL Playground.

**Expected behavior?**

Explore Prisma API in GraphQL Playground.

**Comment by nikolasburk** [comment]
Hey @guog, could you please share which version of the [GraphQL Playground](https://github.com/prismagraphql/graphql-playground) you're using and potentially update to the latest release.

**Comment by guog** [comment]
@nikolasburk Thank you for your reply.

My GraphhQL Playground version is **1.5.0**.

I upgraded GraphQL Playground to the latest version **1.5.3** and found that the problem was solved.
