### ISSUE TITLE
OS Window bug

### ISSUE THREAD

**Issue by OGNeutron** [prismagraphql/prisma#2471]
I've been all week trying to get prisma deploy and graphql codegen to work, so I decided to use Ubuntu 18.04 and it just worked, so it seems there's a bug for Windows.

OS Win 1709.

**Comment by OGNeutron** [comment]
Any word on this issue?

**Comment by divyenduz** [comment]
Partially resolved - https://github.com/graphql-cli/graphql-cli/pull/311. 

`graphql codegen` command should run when manually used on windows.

`prisma deploy` does not call hooks on windows yet, we are working on a fix. 

Closing this in favor of https://github.com/prismagraphql/prisma/issues/2494 which will be closed when all codegen related issues for windows are resolved.
