### ISSUE TITLE
Support Update Mutations like count_add or count_reduce in field Int ?

### ISSUE THREAD

**Issue by baby1990** [prismagraphql/prisma#2476]
I love this frameWork! But I got some problem when i tried to use it to design a online market. I can't deal with some data in mutations, such as the amount of a product.
Is there some mutations like this:

```
mutation {
    updateProduct(
        where: {
            id: "ID"
        }, 
        data: { 
           salesAmount: { 
               count_add: 1
           },
           stockQuantity: { 
              count_reduce: 1 
           }
        }
    )
}```

**Comment by marktani** [comment]
Thanks a lot for this feature request. There are some discussions around current work arounds for this [in the Forum](https://www.prisma.io/forum/c/questions), and we are thinking about adding atomic operations directly into the Prisma API. You can follow [this feature request](https://github.com/graphcool/prisma/issues/1349) to stay notified of our progress here 🙂
