### ISSUE TITLE
FetchError: request to http://localhost:4466/management failed, reason: connect ECONNREFUSED 127.0.0.1:4466

### ISSUE THREAD

**Issue by jurajkrivda** [prismagraphql/prisma#2479]
Hi I followed this tutorial https://github.com/prismagraphql/prisma/blob/master/docs/1.8/03-Tutorials2/06-Deploy-Prisma-Servers/03-Digital-Ocean-(manual).md on prisma/1.8.3 and Docker version 18.03.1-ce, build 9ee9f40 and I got this error FetchError: request to http://localhost:4466/management failed, reason: connect ECONNREFUSED 127.0.0.1:4466.

**Comment by marktani** [comment]
Hey @jurajkrivdam, this error is generally thrown if there is a problem during the Prisma server setup.
Can you share the logs from your Docker container? This will hopefully reveal more information as to what goes wrong.
