### ISSUE TITLE
Deploying to local without internet connection throws errors

### ISSUE THREAD

**Issue by Huvik** [prismagraphql/prisma#2480]
# Bug Report

**Current behavior**
When you turn internet connection off and try to deploy you get: 
![](https://i.imgur.com/812nGKD.png)
**Reproduction**
Turn off wifi and try to deploy you get error for each step of deployment when trying to deploy to local prisma instance
> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

**Expected behavior?**
When deploying without internet ignore prisma plugin and don't make any request to `https://api.cloud.prisma.sh/`

**Comment by divyenduz** [comment]
@Huvik : Have you tried this with the latest Prisma CLI. Now, the CLI emits a warning asynchronously but the deployment to local proceeds. Does that sound alright to you? Any feedback on how the process can be improved 🙂

**Comment by marktani** [comment]
This was fixed in `1.12`.
