### ISSUE TITLE
Prisma instance resolvers do not conform generated schema (v 1.8)

### ISSUE THREAD

**Issue by terion-name** [prismagraphql/prisma#2482]
# Bug Report

Prisma instance contains more resolvers, then types, presented in generated schema

**Reproduction**

My usecase is maybe strange, but nevertheless. I need to make a generic `GraphQLSchema` (`executable schema`) from `Prisma` instance.  Here is a code snippet:

```js
export function getPrismaGeneratedSchema(driver: string = "mysql", generatedPath = "src/schema/generated"): string {
  // schema was previously written to file with schema print:
  // await introspectSchema(new HttpLink({uri: prismaEndpoint, fetch}));
  return fs.readFileSync(path.join(generatedPath, `${driver}.graphql`), "utf8");
}

export function prismaExecutableSchema(
    prismaInstance: Prisma,
    driver: string = "mysql",
    generatedPath = "src/schema/generated"
): GraphQLSchema {
    const typeDefs = getPrismaGeneratedSchema(driver, generatedPath);
    return makeExecutableSchema({
      typeDefs,
      resolvers: {
        Query: prismaInstance.query,
        Mutation: prismaInstance.mutation,
        Subscription: prismaInstance.subscription,
      }
    });
}
```

The problem is in `Subscription` section:
```
EError: Subscription.articles defined in resolvers, but not in schema
```

Schema contains subscriptions **only** on single objects (e.g. Article, Tag, Category), while Prisma instance contains resolvers also on collections (e.g. Articles, Tags, Categories)

**Expected behavior?**

Or generated schema contains subscriptions on collections too, or Prisma instance contains subscriptions on single objects only

**Comment by marktani** [comment]
Can you share a repository where this discrepancy happens?

It doesn't happen in the boilerplate projects for example.

`prisma.ts`:

https://github.com/graphql-boilerplates/typescript-graphql-server/blob/90a03432244475eb99b3936ca676d7eb5587e375/advanced/src/generated/prisma.ts#L468-L471

`prisma.graphql`:

https://github.com/graphql-boilerplates/typescript-graphql-server/blob/master/advanced/src/generated/prisma.graphql#L402-L405

Both the TypeScript bindings and the Prisma API only expose the top-level subscriptions `user` and `post`.
