### ISSUE TITLE
Can't spin up paid Prisma Cloud server

### ISSUE THREAD

**Issue by obibring** [prismagraphql/prisma#2483]
# Bug Report

**Current behavior**
I'm attempting to spin up a paid Prisma Cloud server, but the server never gets past the "Provisioning" stage. I have been unable to get a server live for 3 days.

**Expected behavior?**
The server should eventually go live and provide a URL.

**Comment by marktani** [comment]
This is tracked here: https://github.com/prismagraphql/prisma-cloud-feedback/issues/147
