### ISSUE TITLE
Docs: dead link to AWS s3 file handling inside GraphCool to Prisma migration

### ISSUE THREAD

**Issue by veksen** [prismagraphql/prisma#2493]
https://www.prisma.io/docs/reference/upgrade-guides/graphcool-to-prisma/file-handling-hahcee3eef

https://github.com/prismagraphql/prisma/blob/master/docs/1.8/04-Reference/09-Upgrade-Guides/01-Graphcool-to-Prisma/05-File-Handling.md

**Comment by marktani** [comment]
Thanks, I updated the link to https://github.com/graphcool/prisma/tree/master/examples/archive/file-handling-s3
