### ISSUE TITLE
prisma login and logging in does not authenticate CLI

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2497]
# Bug Report

**Current behavior**

* don't be logged in the CLI
* don't be logged in the browser
* run `prisma login`
* login using Github

result: you are now logged in in the browser. Terminal still says

> Opening https://app.prisma.io/cli-auth?secret=SECRET in the browser

and you are not authenticated in the CLI.

**Expected behavior?**

After logging in in the browser, your CLI is authenticated.

**Comment by marktani** [comment]
This is still an issue.

**Comment by johannpinson** [comment]
I got the same issue.
It try to login first on the dashboard, and the made a `prisma login` but there is no change.

**Comment by johannpinson** [comment]
As talked with @marktani, I have the same bug on a fresh install of prisma (v1.11.0)

After some tests (directly in my global `node_modules`), it looks like this transpiled code doesn't manage well the `await/async` logic into `generator/yield`.
I add some `this.out.log(xx)` to get some information but that block the rest of the script but it allows to receive the token availability to finish the login.

Maybe this PR will solve this bug when it will be publish:
https://github.com/prismagraphql/prisma/pull/2596

**Comment by ankerbachryhl** [comment]
Hi!

I have the same problem and I'm a little unsure about how you solved it @johannpinson ?

Thank you in advance :)

**Comment by ankerbachryhl** [comment]
Still having the problem and can't really proceed with my project before solving it. Any update?

**Comment by ankerbachryhl** [comment]
Ok for others who are having the same problem:

I solved it by installing version 1.10.2 instead of 1.11 because it works in version 1.10.2 👍 
After I logged in I then upgraded to 1.11 where I was because of the cloud session key still logged in.

**Comment by marktani** [comment]
We fixed the GitHub login logic and fixed another problem which caused more login problems [here](https://github.com/prismagraphql/prisma/pull/2745).
