### ISSUE TITLE
split schema.graphql to several files in a large application

### ISSUE THREAD

**Issue by f89688563** [prismagraphql/prisma#2513]
Here, I had splited the schema.graphql to several files in my application and got the error Type "Query" was defined more than once, what should I do to solve the error.
The code.
new GraphQLServer({
  typeDefs: ['src/types/schema.graphql', 'src/types/user.graphql'],
  resolvers,
  resolverValidationOptions: {
    requireResolversForResolveType: false
  },
})

**Comment by mbaranovski** [comment]
Hi @f89688563 
You can take you **schema.graphql** as an entry schema and then import other schemas into it.
For example:
**schema.graphql**:
```
# import * from "user.graphql"
# import * from "someOtherSchema.graphql"

schema {
  query: Query
  mutation: Mutation
}
```
Creating new GraphQLServer:
```
new GraphQLServer({
typeDefs: 'src/types/schema.graphql',
resolvers,
resolverValidationOptions: {
requireResolversForResolveType: false
}
})
```

GraphQLServer constructor is using **importSchema** from **graphql-import** when evaluating typeDefs, so the imports(# comments) will be resolved.

**Comment by f89688563** [comment]
@mbaranovski  thanks.
# import * from "user.graphql"
# import * from "post.graphql"
schema {
  query: Query
  mutation: Mutation
}
got the Error: "Query" defined in resolvers, but not in schema

when I changed like 
# import Query.* from "post.graphql"
# import Mutation.* from "post.graphql"
# import Query.* from "user.graphql"
# import Mutation.* from "user.graphql"
it works well, but I think it's not the good way, do you have any good idea?

**Comment by hajocava** [comment]
Full Example Graphql, Mongo, Express, Apollo-Server 
https://github.com/hajocava/Graphql-Template﻿
