### ISSUE TITLE
Clarification of terms

### ISSUE THREAD

**Issue by heymartinadams** [prismagraphql/prisma#2527]
# Feature Request

**What feature are you missing?**
Greater clarity as to the terms used inside the Prisma CLI and console. Between terms such as `service`, `server`, `stage`, `workspace`, `cluster`… the setup is beginning to confuse me. 

**How could this feature look like in detail? Tradeoffs?**
I would appreciate it if Prisma could either:

1. Explain them during the onboarding process and/or inside the console **as if to a ten year old** (people won’t be offended if you err on the side of clarity), or
2. whittle down the terms to only one or two, or
3. rename them for greater clarity…

**Comment by nikolasburk** [comment]
Hey @heymartinadams, thanks a lot for opening this issue! We're aware that our docs have been very much lacking in that regard and terminology partly was outdated and inconsistent. We've just released a beta version of our new docs which you can find here: https://docs-beta.prisma.io/

In the new docs, we're a lot more consistent with terminology and the `Understand Prisma` chapter hopefully helps to clear your confusions. We're also planning to add a glossary soon to create an overview of the most important terminology!

Please reopen an issue if you see more things we can do to improve this!

**Comment by heymartinadams** [comment]
Way to go, @nikolasburk 🎉
