### ISSUE TITLE
transaction & rollback

### ISSUE THREAD

**Issue by j-colter** [prismagraphql/prisma#2530]
```js
Mutation: {
  createDraft: async (_, args, context, info) => {
   return context.prisma.transaction(async () => {
      const draft = await context.prisma.mutation.createDraft(args, info);
      // do something ...
      if (flag) throw new Error('create a draft error...');
      return draft;
    })
  }
}
```
Does it support this situation, the transaction will auto commit or rollback?

**Comment by marktani** [comment]
A mutation will either commit or not. When would a mutation need to be rolled back?

**Comment by f89688563** [comment]
@marktani  I hope the prisma could auto callback if a mutation throws error in a resolver that has several creates or updates and none error auto commit.
