### ISSUE TITLE
Unable to export from Graphcool 

### ISSUE THREAD

**Issue by inxeptionjake** [prismagraphql/prisma#2543]
# Bug Report

**Current behavior**
Using the command line tool, I ran "graphcool export" on my Graphcool project (cj7jjoynu05xx015689nwnetl).  I get the following response:

root@ip-10-32-7-17:/home/ubuntu/repo/noribachi/v3.0.X_branch/inxeption-deploy# graphcool export
Downloading nodes... ✔
 ▸    The download of nodes failed. You may get fragmented data. Request ID:
 ▸    us-west-2:simple:cjhtjpd8l1dbe0181q47p5saw

Downloading lists... 70ms
Downloading relations... ✔
 ▸    The download of relations failed. You may get fragmented data. Request ID:
 ▸    us-west-2:simple:cjhtjpde91eas0195cepgzyd4

Zipping export...
Zipping export... 20ms
Exported service to export-2018-05-30T20:10:32.832Z.zip
You can import it to a new service with
  $ graphcool import --source export-2018-05-30T20:10:32.832Z.zip --target target-name
root@ip-10-32-7-17:/home/ubuntu/repo/noribachi/v3.0.X_branch/inxeption-deploy#

After this error,  there is a zip with folders (lists/, nodes/, and relations/) . All the folders are empty except lists, which has one file (000001.json) with "{"valueType":"lists","values":[]}" as the contents.

When I run export command on other Graphcool projects I see all the data and am able to import those projects into Prisma.

**Reproduction**

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

**Expected behavior?**
Export to give zip with all data so I can move to Prisma.

**Comment by marktani** [comment]
You are running into https://github.com/graphcool/graphcool-framework/issues/456. You can set up a VPN connection so your IP is near to the region if your project.

Please report further problems you encounter with Graphcool Framework in this repository:https://github.com/graphcool/graphcool-framework. Thanks! :slightly_smiling_face:
