### ISSUE TITLE
Error when trying to seed database using script file

### ISSUE THREAD

**Issue by 2wce** [prismagraphql/prisma#2549]
# Bug Report

**Current behavior**
When I run the prisma seed command the following error message pops up in the terminal if I want to seed the database with a script file. 
```
Seeding based on yarn seed !
 ▸    cross_spawn_1.default is not a function
```
**Reproduction**
Create a script to seed the database and reference it in prisma.yml as
```
seed:
  run: yarn seed
```
with the yarn seed being a script in my package.json which runs the actual file
```
  "scripts": {
    "seed": "ts-node database/seed.ts"
  },
```
If I run yarn seed on it's own the database is seeded. Error shows up when prisma seed tries to run the same command.

**Expected behavior?**
Should seed database with mutations specified in script file

**Comment by jhalborg** [comment]
Note, dublicate report [here](https://github.com/prismagraphql/prisma/issues/2554) - both authors came here from same forum discussion at @marktani 's request 😄 Contributors can let either of us know which one to close

**Comment by divyenduz** [comment]
Fixed here in [alpha](https://www.prisma.io/blog/improving-prismas-release-process-yaey8deiwaex/) channel - https://github.com/prismagraphql/prisma/pull/2569

Will be released as per the new [release process](https://www.prisma.io/blog/improving-prismas-release-process-yaey8deiwaex/).
