### ISSUE TITLE
Error When Omitting @relation In Schema Relationship - Prisma 1.8.3

### ISSUE THREAD

**Issue by dsoraluz-carecloud** [prismagraphql/prisma#2550]
When defining the following schema example:

```
type Form {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  isPublished: Boolean! @default(value: "false")
  title: String!
  content: Json!
  author: User! @relation(name: "FormsByUser")
  lastEditedBy: User!
}

type User {
  id: ID! @unique
  email: String! @unique
  awsSub: String! @unique
  firstName: String!
  lastName: String!
  forms: [Form!]! @relation(name: "FormsByUser")
}
```
An error is thrown on prisma deploy that reads:

`The relation field `lastEditedBy` must specify `@relation` directive: @relation(name: "MyRelation")``

When reviewing the [prisma docs](https://www.prisma.io/docs/reference/service-configuration/data-model/data-modelling-(sdl)-eiroozae8u/#the-@relation-directive) on the matter it specifies that omitting the @relation directive is allowed and if done so the relationship is taken as a one-to-many relationship rather than a many-to-many which is exactly what we want.

What we are trying to achieve is the following:

- a Form has an author (User) and a Form is last edited by a User. 
- The lastEditedBy field can or can not be the same User that created it.
- when querying a Form and it's properties I want to be able to get the information for the User that last edited it From the lastEditedBy property.

Note: This behavior can be achieved by using @relation but that will create a stale data field on the User type that will never be used. See below.

```
type Form {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  isPublished: Boolean! @default(value: "false")
  title: String!
  content: Json!
  author: User! @relation(name: "FormsByUser")
  lastEditedBy: User! @relation(name" "EditedByUser")
}

type User {
  id: ID! @unique
  email: String! @unique
  awsSub: String! @unique
  firstName: String!
  lastName: String!
  forms: [Form!]! @relation(name: "FormsByUser")
  editedForms: [Form!] @relation(name" "EditedByUser")
}
```

I will never run a query where I will want to see "all the forms that a User has edited".  Rather, I will want query a form and then see "who is the last User that edited it".

So my question to the dev team, is there a way to omit the @relation directive and thereby creating the extra data field in the User type for edited forms?

**Comment by mponizil** [comment]
I'm not 100% sure, but my guess is that you don't need to have the `editedForms` field on `User` at all. The only reason you do need a `@relation` annotation on `Form#lastEditedBy` is because there's another field (`author`) with a relation to the same object type (`User`). So the `@relation` for `lastEditedBy` is just to disambiguate.

You should be able to just remove `editedForms: [Form!] @relation(name: "EditedByUser")`. You may also wish to change the relation name from `EditedByUser` to `LastEditedByUser`.

**Comment by do4gr** [comment]
Hey, @dsoraluz-carecloud,

@mponizil is correct, you do not need to create the backrelationfield, but you need to provide the relation directive to disambiguate. So this schema deploys without a problem:

```graphql
type Form {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  isPublished: Boolean! @default(value: "false")
  title: String!
  content: Json!
  author: User! @relation(name: "FormsByUser")
  lastEditedBy: User! @relation(name: "EditedByUser")
}

type User {
  id: ID! @unique
  email: String! @unique
  awsSub: String! @unique
  firstName: String!
  lastName: String!
  forms: [Form!]! @relation(name: "FormsByUser")
}
```

**Comment by dsoraluz-carecloud** [comment]
Yes, the above works. Thanks for the help in clearing that up.
