### ISSUE TITLE
Homework type name creates 2 Queries with the same name

### ISSUE THREAD

**Issue by makmm** [prismagraphql/prisma#2552]
# Bug Report

**Current behavior**

⚠ All fields within 'Query' type should have unique names! Non-unique fields: 'homework'.
(tries to make 2 queries types with the same name, and fails because GraphQL)

**Reproduction**

```graphql
type Homework {
  id: ID! @unique
}
```

**Expected behavior?**

Just work.. :/

**Comment by andrewjmead** [comment]
Do you have a zip you could share? I wasn't able to recreate this on my machine.

**Comment by makmm** [comment]
@andrewjmead Yup. Here:
[backend-graphql.zip](https://github.com/prismagraphql/prisma/files/2060656/backend-graphql.zip)
```
# To produce:
source .env.dev
prisma deploy
yarn update-schema # or npm run
```

**Comment by marktani** [comment]
Hey @makmm, please use a different name than `homework`. The plural form of `homework` is `homework`, leading to a name clash for the two queries for fetching one and many `Homework` nodes respectively:

```
type Query {
  homework: Homework
  homework: [Homework!]!
}
```
