### ISSUE TITLE
Warning: Management API authentication is disabled.

### ISSUE THREAD

**Issue by peterschussheim** [prismagraphql/prisma#2561]
# Bug Report

**Current behavior**
Prisma server deployed to ECS/Fargate emits the following log message constantly:

```bash
Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
```

**Reproduction**
- [`MySQL CloudFormation` template](https://github.com/prismagraphql/database-templates/blob/master/aws/mysql.yml)
- ECS container running `prismagraphql/prisma:1.8.3` image, RDS instance is `mysql`.
- [`fargate CloudFormation` template](https://github.com/prismagraphql/prisma-templates/blob/master/aws/fargate.yml)

**Expected behavior?**

I expect the management api auth mechanism to work as described.

Please let me know if more info is needed.

Thanks,
Peter

**Comment by marktani** [comment]
Thanks a lot for bringing this up! This is covered in this issue already: https://github.com/prismagraphql/prisma-templates/issues/7.

We'll soon look into improving this part of the template 🙂
