### ISSUE TITLE
Deploys to existing service on custom servers on prisma cloud fail for prisma >1.8

### ISSUE THREAD

**Issue by ntziolis** [prismagraphql/prisma#2572]
**Bug**
Using 1.8.4 to deploy to an existing service does NOT work on custom server on prisma cloud

**Reproduction**
```
prisma deploy -d
Creating stage prod for service circula!

ERROR: Service with name 'circula' and stage 'prod' already exists

{
  "data": {
    "addProject": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "path": [
        "addProject"
      ],
      "code": 4005,
      "message": "Service with name 'circula' and stage 'prod' already exists",
      "requestId": "circula_niko:management:cji0e0md333qdqk09698vczqs"
    }
  ],
  "status": 200
}
```

**Expected behavior?**
Either:
- automatically migrate schema name from `graphcool` to `managment` when prisma cloud servers are updated
- or allow to specify a custom schema name (like in the docker compose file but for prisma cloud)

**Comment by dpetrick** [comment]
Hello @ntziolis,

> automatically migrate schema name from graphcool to managment when prisma cloud servers are updated

As easy as it sounds, it is _not_ easy to do automatically. Additionally, we explicitly decided against implementing magic migrations to avoid confusion. In fact, we implemented the "custom schema name" you mentioned a while ago: https://github.com/prismagraphql/prisma/releases/tag/1.8.0

Cloud servers you created are expected to be unaffected by the 1.8 release, as the old `graphcool` schemas are configured for cloud deployments before 1.8 that upgraded to 1.8.x.

Can you please elaborate on your specific problem that you're facing?

**Comment by ntziolis** [comment]
I cannot deploy to our prisma cloud hosted production server anymore using prisma CLI >1.8. Error is the one you see above. Both CLI and server are on 1.8.4. Removing the service is not an option as its our production system. 

> Cloud servers you created are expected to be unaffected by the 1.8 release, as the old graphcool schemas are configured for cloud deployments before 1.8 that upgraded to 1.8.x.

This does not seem to be the case at least not in our specific deployment. We did have issues migrating to 1.6.3 / 1.6.4 (was in contact with @marktani on that previously. Once it was possible to migrate servers again we moved it up to 1.8.4 from 1.6.something.

Maybe during that jump something went wrong?

**Comment by ntziolis** [comment]
Deleted my last comment by mistake. Did you do something as it suddenly started working again after being blocked for last 2 days?

**Comment by ntziolis** [comment]
Ok so I don't know whats going on anymore:
- it started working again for about 5min (after 100% failure rate in the last 2 days)
- and now we are back to the above error message

Are you looking into this on your end, if so please tell me because Im seeing ghosts by now :)

**Comment by dpetrick** [comment]
I looked at the server configurations and everything is as expected. The error also doesn't indicate that it's using the wrong schema for deployment, otherwise it would return an existing service `circular@prod`, it seems like a CLI issue. I am in no position at the moment to debug the CLI side, but I will take a closer look at the server setup.

**Comment by dpetrick** [comment]
It might be a bugged dry run flag in the CLI. Just to make sure: Deploying without the dryrun flag also doesn't work?

**Comment by ntziolis** [comment]
Same without `-d`.

Here is what I have been seeing the last 10 mins:
- 1 out of 20 times it comes back with the correct result (outlining the schema changes)
- no matter if -d or not

If I hit the deploy service in a loop really hard it seems to increase the success rate slightly but this just feels wrong. This smells like a race condition in the CLI if everything is fine server side.

Im on windows, knowing you guys are all non windows maybe this is windows specific?

**Comment by ntziolis** [comment]
Im getting slightly different errors sometimes now:

```
ERROR: Project not found: 'management@default'

{
  "errors": [
    {
      "message": "Project not found: 'management@default'",
      "code": 3016,
      "requestId": "circula_niko:api:cji0k4o509mxa0934mimkypaf"
    }
  ],
  "status": 200
}
```

**Comment by dpetrick** [comment]
Can you try if it is better now?

**Comment by ntziolis** [comment]
Yes it now went through 5 successive times! Thank you.

**Comment by dpetrick** [comment]
Closing for now. Please reopen if you have issues again in the next hours.

**Comment by ntziolis** [comment]
@dpetrick No need to reopen again, just wanted to add some additional info. I think I was trigger happy when performing the update. Meaning its possible to trigger another update while one update is performing (at least the UI allows me todo it, not sure if the backend does). I did so because the update was not competed after 20+minutes. And I didnt get any visual indication that its still ongoing so I assumed it might not have gone through

Suggestion:
Disable ability to execute additional updates while one update is ongoing (in prisma console UI).

**Comment by grantpant** [comment]
Just in case it helps anyone else, I was getting the error
`ERROR: Service with name <SERVICE> and stage <STAGE> already exists`
It decided to work after shutting down and reopening the cmder console.

**Comment by tanujdoshi** [comment]
> @dpetrick No need to reopen again, just wanted to add some additional info. I think I was trigger happy when performing the update. Meaning its possible to trigger another update while one update is performing (at least the UI allows me todo it, not sure if the backend does). I did so because the update was not competed after 20+minutes. And I didnt get any visual indication that its still ongoing so I assumed it might not have gone through
> 
> Suggestion:
> Disable ability to execute additional updates while one update is ongoing (in prisma console UI).

hello i ma new to prisma , can you tell me how you can solve this error , i m getting this from last few days , and still i cant solve it!!
