### ISSUE TITLE
Setup a Prisma server by connecting non-empty MySQL database

### ISSUE THREAD

**Issue by ahsannaveed007** [prismagraphql/prisma#2595]
# Bug Report
N/A

**Current behavior**
N/A

**Reproduction**
N/A

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

**Expected behavior?**
Documentation enhancement request: Would like to see this under tutorial section: https://www.prisma.io/docs/tutorials/setup-prisma/connect-db-with-data/mysql-vuthaine2f

**Comment by marktani** [comment]
This is an open feature request that we'll implement soon - you can track the progess here: #2506.

I'll add a respective note to the tutorial to make this clear. Thanks for your feedback!

**Comment by ahsannaveed007** [comment]
Thanks, @marktani much appreciated 👍
