### ISSUE TITLE
Does Prisma WS endpoint support queries and mutations?

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [prismagraphql/prisma#2606]
Does Prisma GraphQL database WebSockets endpoint support queries and mutations or only subscriptions?

I'm trying to send queries and mutations to Prisma over WebSockets (using `wss://`, not `https://` endpoint), but get the following error:

> The provided query doesn't include any known model name. Please check for the latest subscriptions API.

**Comment by marktani** [comment]
No, it doesn't 🙂
Would be great if you can open an according feature request for this!

**Comment by FluorescentHallucinogen** [comment]
@marktani Done, see #2607. :wink:
