### ISSUE TITLE
Add a scalar type for UUID

### ISSUE THREAD

**Issue by mavilein** [prismagraphql/prisma#2615]
# Feature Request

**What feature are you missing?**
We need a new scalar type for UUIDs in our schemas. This is required in order to improve our support for existing databases. Specifically this will address the bugs: https://github.com/prismagraphql/prisma/issues/2503 and https://github.com/prismagraphql/prisma/issues/2447.

**How could this feature look like in detail? Tradeoffs?**
This will enable the following SDL:
```
type Todo {
  id: UUID! @unique
}
```

This feature needs to accomplish the following things:
- allow to use the `UUID` type in the SDL
- parameters of type `UUID` must be validated according to [RFC 4122](https://tools.ietf.org/html/rfc4122) when entering the system
- instead of generating CUIDs for nodes we must generate UUIDs when this new type is used
- a connector with `migrations: true` must be able to handle this new ID type as well. It has to create tables for models with the correct underlying SQL type.

**Comment by marktani** [comment]
This is part of the `1.11.0-beta`: https://github.com/prismagraphql/prisma/releases/tag/1.11.0-beta. [Here](https://www.prisma.io/docs/reference/prisma-servers-and-dbs/prisma-servers/overview-eu2ood0she#installing-prisma-beta) is more information about setting up the beta version.

**Comment by do4gr** [comment]
This feature is available in stable now.
