### ISSUE TITLE
Document --force flag

### ISSUE THREAD

**Issue by sorenbs** [prismagraphql/prisma#2616]
Prisma 1.6.1 introduced warnings for deploys of potentially destructive changes. the `--force` flag was introduced to instruct the cli to continue with the deploy anyway.

Release notes: https://github.com/prismagraphql/prisma/releases/tag/1.6.1

**Comment by nikolasburk** [comment]
old docs: https://www.prisma.io/docs/reference/cli-command-reference/database-service/prisma-deploy-kee1iedaov
new docs: https://docs-beta.prisma.io/1.13/develop-prisma-service/prisma-cli/command-reference-xcv9/
