### ISSUE TITLE
Issue with graphql-import 

### ISSUE THREAD

**Issue by OGNeutron** [prismagraphql/prisma#2638]
import FriendsRequestsSubscriptionPayload from “./prisma.graphql” 

I am trying to import a type from the generated prisma file to my schema.graphql file, but I get this error:

Error: Type “NotificationOrderByInput” not found in document.

And If I do try to import it I get the same error, though I shouldn’t have to as graphql import is supposed to recursively bring in what’s needed.

**Comment by marktani** [comment]
Hi.

Please provide this bug report filling out [the bug report template](https://github.com/prismagraphql/prisma/issues/new?template=bug_report.md).

Thanks.

**Comment by marktani** [comment]
Moving the conversation here: https://github.com/prismagraphql/prisma/issues/2639
