### ISSUE TITLE
Postgres - Cannot Limit Max Connections (1.10b1)

### ISSUE THREAD

**Issue by techalchemy** [prismagraphql/prisma#2640]
Let me start by saying thanks for such an amazing project.  Apart from the quirk about SSL currently, configuring this was actually incredibly easy and I believe this addresses most of our current complaints working with ORMs but using them as access layers.  Seriously, this is awesome, good job guys.

### Description

Querying prisma fails when using a hobby heroku node -- the postgres adapter is aggressively consuming connections on a hobby heroku instance when querying nested endpoints -- configuring the relevant limiting settings seems not to help.

### Reproducing
1. Run `npm install -g prisma@1.10.0-beta.1`
2. Initialize against an existing postgres database.
3. Swap `docker-compose.yml` to point at `prismagraphql/prisma:1.10-beta-1`
4. Add the following keys under the `environment` section:
```
      SQL_CLIENT_CONNECTION_LIMIT: 2
      SQL_INTERNAL_CONNECTION_LIMIT: 2
      SQL_LOGS_CONNECTION_LIMIT: 2
```
5. Add `ssl: true` to the postgres section (this is why we are using the beta version)
6. Run `docker-compose up -d` followed by `prisma deploy` and `prisma playground`
7. Run a query with a few nested relationships/endpoints

### Expected Behavior
Connections to be limited or scaled down if there are no more to allocate (?) magic would be nice but I don't mind an environment variable 

#### Heroku Screenshot

![image](https://user-images.githubusercontent.com/954310/41500894-6bc70bbc-7168-11e8-8a3a-3bd32315ff69.png)

#### Playground Result
<details>

```json
{
  "data": null,
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:api:cjihns92a00060a086cxclxti",
      "path": [
        "support_cases"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "requestId": "local:api:cjihns92a00060a086cxclxti"
    }
  ]
}
```
</details>

#### Playground Debug Log
<details>

```console
Serving playground at http://localhost:3000/playground
  cli not flushing +404ms
  express:router dispatching GET /playground +9s
  express:router query  : /playground +1ms
  express:router expressInit  : /playground +0ms
  express:router trim prefix (/playground) from url /playground +1ms
  express:router <anonymous> /playground : /playground +0ms
  finalhandler cannot 404 after headers sent +4ms
```
</details>

#### Docker Log
<details>

```console
Jun 16, 2018 5:03:30 PM org.postgresql.Driver connect
SEVERE: Connection error:
org.postgresql.util.PSQLException: FATAL: too many connections for role "<username>"
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
        at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
</details>

### Version Information
 - OS: `Lubuntu 18.04`
 - `prisma` CLI: `prisma/1.10.0-beta.1 (linux-x64) node-v10.0.0`
 - Prisma Server: `1.10.0-beta-1`

#### docker-compose.yml
<details>

```yaml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.10-beta-1
    restart: always
    ports:
    - "4466:4466"
    environment:
      SQL_CLIENT_CONNECTION_LIMIT: 2
      SQL_INTERNAL_CONNECTION_LIMIT: 2
      SQL_LOGS_CONNECTION_LIMIT: 2
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: <scrubbed>.compute-1.amazonaws.com
            port: '5432'
            ssl: true
            SQL_CLIENT_CONNECTION_LIMIT: 2
            SQL_INTERNAL_CONNECTION_LIMIT: 2
            SQL_LOGS_CONNECTION_LIMIT: 2
            database: <scrubbed>
            schema: public
            user: <scrubbed>
            password: <scrubbed>
            migrations: false
```

</details>

**Comment by pspeake87** [comment]
+1

**Comment by stephen-bunn** [comment]
+1 Running into the same issue

**Comment by stephen-bunn** [comment]
@techalchemy I was able to limit connections using the parameter `connectionLimit` in the `PRISMA_CONFIG`. I found it [here](https://github.com/prismagraphql/prisma/blob/master/server/connectors/api-connector-postgresql/src/main/scala/com/prisma/api/connector/postgresql/database/Databases.scala#L44)

```yaml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.11-alpha
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: $DB_HOST
            port: '5432'
            database: $DB_NAME
            schema: public
            user: $DB_USER
            password: $DB_PASS
            migrations: false
            ssl: true
            connectionLimit: 2
```

**Comment by mavilein** [comment]
Hey @techalchemy,

thanks for providing such a thorough description and analysis. First of i would like to encourage you to use config format as mentioned by @stephen-bunn. The format you used is outdated. It is clearly on us that we have not documented it properly yet. We created the issue #2653 to do this.

But your analysis is correct and we are creating too many connections. The exact behaviour varies depending on the version of the Prisma server:
- A version of `1.11` or below creates actually 10 times the connections as specified (just like you observed). 
- The version `1.12` that will be available tomorrow contains a first improvement. Due to this change Prisma will create 2 times the connections as specified. 

I will have a look this week how we can fix this issue for real so it just works as expected. I hope that you can work around this issue until we have fixed the issue.

**Comment by marktani** [comment]
The `1.12` version as described by @mavilein has been released to stable today.
