### ISSUE TITLE
Adding required fields with default to schema fails

### ISSUE THREAD

**Issue by terion-name** [prismagraphql/prisma#2644]
Prisma 1.9, mysql

```graphql
type ArticleTranslation {
    lang: String!
    title: String!
    teaser: String! @default(value: "") # this was added
    body: String!
}
```

Deployment error:

```
[{"type":"ArticleTranslation","field":"teaser","description":"You are making a field required, but there are already nodes that would violate that constraint."}]
```

Obviously, that should be like this — adding default value on DB non-nullable field created column filled with defaults on existing rows

**Comment by marktani** [comment]
This is the current expected behaviour. Your suggestion makes a lot of sense and has been brought up here: #2323.
