### ISSUE TITLE
Unable to deploy to cluster running 1.10.0

### ISSUE THREAD

**Issue by kgoggin** [prismagraphql/prisma#2663]
**Describe the bug**
I'm attempting to upgrade to Prisma 1.10. After bumping the version in my docker-compose file, and the cli version, I attempted to run `prisma deploy`, but received an error:

```
 ▸    Invalid Version: 1.1
```

**To Reproduce**
1. Update prisma image in docker-compose.yml to `1.10.0`
2. Update prisma cli to latest (1.10.0)
3. Run `prisma deploy`

**Expected behavior**
Deployment proceeds

**Additional context**
I did some troubleshooting and I believe the issue lies with [this regex](https://github.com/prismagraphql/prisma/blob/1dee235f82f7481828d1ae0b3a1ab0c8e95ebe3a/cli/packages/prisma-cli-core/src/commands/deploy/index.ts#L261).

When I log the result of `cluserMatch`, I get:

```
1.10.0
1.1
0.0
```
So, when `clusterMatch[1]` is passed to the semver check on line 281, that module throws the error from above (`Invalid Version: 1.1`). It seems the regex match is stripping the `0`s.

I'm terrible with regex or I'd try to fix it myself, but hopefully that'll at least point you in the right direction!

I'm going to try using the most recent beta version for my docker image and see if that'll work.

**Comment by kgoggin** [comment]
Just tried knocking the docker image back to `1.10-beta` and the deployment worked, for anyone who needs a work-around while this gets fixed!

**Comment by timsuchanek** [comment]
Fixed in 1.10.1. Please let us know if you still have that issue, then we reopen it!
