### ISSUE TITLE
Request clarification: Aurora Postgres, Aurora MySQL/MariaDB

### ISSUE THREAD

**Issue by DavidJFelix** [prismagraphql/prisma#2667]
**Is your feature request related to a problem? Please describe.**
The documentation lists all planned databases such as Cassandra and Cockroach DB but makes no mention of AWS Aurora. Aurora has Postgres and MySQL compatible variants and claims fully compatible, unlike some databases which are only wire/query compatible.

**Describe the solution you'd like**
To know if these databases are currently believed to work as intended, or if further work will need to be done.

**Describe alternatives you've considered**
Just trying it and crossing my fingers, but that seems like a bad way to operate.

**Comment by marktani** [comment]
Yes, Aurora MySQL and Postges are supported.
