### ISSUE TITLE
Paid Prisma server disappeared from account

### ISSUE THREAD

**Issue by obibring** [prismagraphql/prisma#2676]
**Describe the bug**
Upon logging into my Prisma account, the Prisma server that I am currently paying for is not listed (only the 2 public servers are listed). There is no indication that my paid server exists, although I can connect to it normally in code.

Please let me know what further information is needed to fix the issue.

**Comment by marktani** [comment]
It seems that you are logged in to a different account. I reached out to your support ticket, let's continue the conversation there.
