### ISSUE TITLE
Wrong link in documentation

### ISSUE THREAD

**Issue by myWsq** [prismagraphql/prisma#2683]
https://www.prisma.io/docs/tutorials/setup-prisma/connect-empty-db/mysql-dusee0nore#step-3:-create-your-prisma-server

![](http://ipic-1253962968.file.myqcloud.com/2018-06-24-173542.jpg)

Refer to localhost 😂

**Comment by nikolasburk** [comment]
Thanks for pointing that ouy @myWsq, just fixed the broken link 👍
