### ISSUE TITLE
When the user has a one-to-many relationship, the server query will report an error

### ISSUE THREAD

**Issue by LuHugo** [prismagraphql/prisma#2707]
**Describe the bug**
When the user has a one-to-many relationship, the server query will report an error.

One user has multiple articles
```graphql
type User {
  id: ID! @unique
  name: String! @unique
  password: String!
  articles: [Article!]! @relation(name:"UserArticles", onDelete: CASCADE)
}
```

```graphql
query {
  login(name:"lyy",password:"123456"){
    user{
      name
    }
  }
}
```

Throw an error message：
```js
{
  "data": null,
  "errors": [
    {
      "message": "Field 'user' of type 'User' must have a sub selection. (line 2, column 3):\n  user(where: $_v0_where)\n  ^",
      "locations": [],
      "path": [
        "user"
      ]
    }
  ]
}
```

The debug logs: 
```
query ($_v0_where: UserWhereUniqueInput!) {
  user(where: $_v0_where)
}
operationName: null
variables:
{
  "_v0_where": {
    "name": "lyy"
  }
}
[GraphQL error]: Message: Field 'user' of type 'User' must have a sub selection. (line 2, column 3):
  user(where: $_v0_where)
  ^, Location: [object Object], Path: undefined
[Network error]: Error: Field 'user' of type 'User' must have a sub selection. (line 2, column 3):
  user(where: $_v0_where)
  ^
Error: Field 'user' of type 'User' must have a sub selection. (line 2, column 3):
  user(where: $_v0_where)
  ^
    at BatchedGraphQLClient.<anonymous> (/Users/luyuyong/relation-test/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:77:35)
    at step (/Users/luyuyong/relation-test/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/Users/luyuyong/relation-test/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/Users/luyuyong/relation-test/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at process._tickCallback (internal/process/next_tick.js:178:7)
```

I try to remove the `info` parameter in the resolver, it will return data, but the articles field does not have data

```js
//before
const user = await ctx.db.query.user({ where: { name } }, info);
//after
const user = await ctx.db.query.user({ where: { name } });
```

**To Reproduce**
1. datamodel.graphql
```graphql
type User {
  id: ID! @unique
  name: String! @unique
  password: String!
  articles: [Article!]! @relation(name:"UserArticles", onDelete: CASCADE)
}

type Article{
  id:ID! @unique
  title: String!
  content: String!
  author: User! @relation(name:"UserArticles", onDelete: SET_NULL)
}
```
2. schema.graphql
```graphql
#import { User } from './generated/prisma.graphql'
type LoginPayload{
  token: String
  user: User
}

type Query{
  login(name:String!, password: String!): LoginPayload!
}
```
3. resolver
```js
const resolvers = {
  Query: {
    async login(root, args, ctx, info){
      const { name } = args;
      const user = await ctx.db.query.user({ where: { name } }, info);
      return {
        token: 'Fake one token',
        user
      }
    }
  }
}
```
4. query 
```graphql
query {
  login(name:"lyy",password:"123456"){
    user{
      name
    }
  }
}
```

**Expected behavior**
Can correctly query the data including the relationship object data.

**Versions (please complete the following information):**
 - OS: `macOS High Sierra  10.13.5`
 - Prisma `prisma/1.10.2 (darwin-x64) node-v10.0.0`
 - Prisma Server: [`1.10.2`]
 - `graphql-cli`, `prisma-binding`, `graphql-yoga`

**Additional context**
```js
"dependencies": {
    "graphql-yoga": "^1.14.10",
    "prisma-binding": "^2.1.0"
  }
```

**Comment by maticzav** [comment]
Hey @LuHugo 👋,

You are experiencing this problem because your `info` object is still in the context of `LoginPayload` whereas you should first reduce it to `User`.

To fix this, you should add a `LoginPayload` resolver and resolve `user` field there.

```ts
const resolvers = {
  Query: {
    async login(root, { name }, ctx, info) {
      // info is in the context of AuthPayload - doesn't work with Prisma
      // (similar to this { token user { id } })
      const user = { id: "userId" };
      // obtain userID alongside the token and forward it
      return {
        token: "Fake one token",
        user
      };
    }
  },
  LoginPayload: {
    async user({ user }, args, ctx, info) {
      // { id } = parent = result from 'login' resolver
      // info is reduced to User (similar to this { id }) - works with Prisma
      return ctx.db.query.user({ where: { id: user.id }}, info)
    },
    // you can omit token resolver here
    // async token({ token }, args, ctx, info) {
    //   return token // just forward it
    // }
  }
};
```

**Comment by LuHugo** [comment]
Thanks brothers, this is really a viable solution, but my token needs to contain other information about the user, like this：
```js
const token = sign({ data: { id: user.id, role: user.role } }, screct, { expiresIn: '1d' });
```

So I have to get user information before I can sign a token.

I don't know if there are other ways to achieve my expectations, or do I need to change my schema structure?

**Comment by maticzav** [comment]
Hey man, no problem! 💪

So, since your `token` relies on pretty specific information about `user` shouldn't rely on the user requesting it or not. (Long story short; you should not forward `info` in such cases).

Besides that, there's nothing wrong with requesting `user` here as well. The only thing is that you will have to define yourself is `info`. But only that in case you are using relational fields. 
> `prisma-binding` by default returns all one-level deep scalars - in your case that could be `role` and `id`, and maybe also `name` if you have it (all direct `Boolean`, `String` etc. fields of your type)

Keep in mind though that your user might request some additional information, maybe a nested structure or something similar about your `user` field. That's why you still need that resolver we talked about above! 🙂

**Comment by LuHugo** [comment]
Yes, I spend a day writing custom resolver info and can achieve my expectations, although not perfect, but it works

I defined a method that takes the target field as a parameter and returns the new info：
```js
// return new info
const userResolverInfo = getObjectTypeFieldResolverInfo('info', info);

let user = await ctx.db.query.user({ where: { openId: openid } }, userResolverInfo);
if (user) {
        token = sign({ data: { id: user.id, role: user.role } }, ctx.screct, { expiresIn: '1d' });
      }
```

**Comment by LuHugo** [comment]
@maticzav 
You're right, it's overly complex, and I should only return user type non-relational fields. If the resolver performs slowly, the AuthPayload type will change to return only fields other than the relation field.
