### ISSUE TITLE
Import must be tolerant of missing node ids when importing scalar lists

### ISSUE THREAD

**Issue by mavilein** [prismagraphql/prisma#2733]
**Describe the bug**
An export of an older Prisma version might contain values for scalar lists that reference a non existent node id. 

**To Reproduce**
1. On an older Prisma version (e.g. 1.5.), create a node with scalar list values. Delete that node afterwards.
2. Export from this version.
3. Import it into a recent Prisma version, e.g. 1.11.
4. The import will crash, because the export contains the scalar list values for the node that has been deleted.

**Expected behavior**
The import must not crash. The import must ignore those errors when importing scalar list values.

**Versions (please complete the following information):**
 - OS: `OS X High Sierra`
 - Prisma Server: `1.11.0`

**Additional context**
I found this bug when i imported the database of Cloud API locally to performance test our import/export.

**Comment by mavilein** [comment]
This spec suggests that this was a somewhat conscious design decision: https://github.com/prismagraphql/prisma/blob/master/server/servers/api/src/test/scala/com/prisma/api/import_export/ListValueImportExportSpec.scala#L44

So it is not clear whether this is a bug. But due to the limitations in old versions of Prisma this is very annoying. We should talk that through.

**Comment by marktani** [comment]
Maybe a local script that cleans up "dangling scalar lists" would be a suitable workaround?

**Comment by mavilein** [comment]
superseded by: https://github.com/prismagraphql/prisma/issues/2738
