### ISSUE TITLE
Typescript definition of Mutations and Queries does not conform to reality

### ISSUE THREAD

**Issue by tomitrescak** [prismagraphql/prisma#2751]
Is there any particular reason why the Query and Mutation functions are generated with 3 parameters only? For example:

```ts
export interface Query {
    authenticate: <T = String>(args: { username?: String, password?: String }, info?: GraphQLResolveInfo | string, options?: Options) => Promise<T> ,
}
```

In reality, these resolver functions have four parameters. So correct way would be:

```ts
export interface Query {
    authenticate: <T = String>(parent: any, args: { username?: String, password?: String }, context: Prisma, info?: GraphQLResolveInfo | string) => Promise<T> {
}
```

I tried searching for the solution but cannot find any. Thanks

**Comment by marktani** [comment]
Issue moved to [prismagraphql/prisma-binding #199](https://github.com/prismagraphql/prisma-binding/issues/199) via [**ZenHub**](https://www.zenhub.com/)
