### ISSUE TITLE
Server side subscriptions custom headers are not being sent

### ISSUE THREAD

**Issue by johhansantana** [prismagraphql/prisma#2758]
**Describe the bug**
When passing the `headers` via the `yaml` configuration file, none of them are being sent to the webhook.

**To Reproduce**
1. Go to your `prisma.yml` file and add a [server side subscription](https://www.prisma.io/docs/reference/server_side-subscriptions/overview-to1ahf0ob6#prisma.yml)
2. do `prisma deploy` and try to invoke your subscription
3. console log the headers on the webhook and you will see that the ones you added to the configuration file are not being sent.

**Expected behavior**
It should be able to send the custom headers via the yaml file.

**Versions (please complete the following information):**
 - OS: `OS X`
 - prisma: `prisma/1.11.1 (darwin-x64) node-v9.7.1`
 - Prisma Server: [e.g. `1.11.1`]

**Comment by marktani** [comment]
I cannot reproduce this on `1.12-beta-1`. I set a header like this:

```yml
subscriptions:
  userChangedEmail:
    webhook:
      url: http://ptsv2.com/t/prisma/post
      headers:
        Content-Type: application/json
        Authorization: Bearer cha2eiheiphesash3shoofo7eceexaequeebuyaequ1reishiujuu6weisao7ohc
    query: |
      subscription {
        user(where: { mutation_in: [CREATED] }) {
          mutation
          node {
            id
            name
          }
        }
      }
```

and it is applied to [the POST request](http://ptsv2.com/t/prisma/d/340001).

**Comment by johhansantana** [comment]
Hi @marktani I'm sorry for the noise of this issue. It appears to be working today... 😞 

PS thanks for the http://ptsv2.com link, really helpful.
