### ISSUE TITLE
Document the management API

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2774]
**Is your feature request related to a problem? Please describe.**

The management API is currently not documented.

**Describe the solution you'd like**

Describe the general purpose of the management API, and its most important queries and mutations.

**Describe alternatives you've considered**

We should highlight that using the CLI is the primary interface to the management API, and that using it directly (especially for mutations) is an advanced use case.

**Comment by nikolasburk** [comment]
This is taken care of in the docs [here](https://docs-beta.prisma.io/1.13/operate-prisma-server/management-api-foe1/)
