### ISSUE TITLE
Can't delete UUID records in PostgreSQL

### ISSUE THREAD

**Issue by pedroalves0030** [prismagraphql/prisma#2799]
**Describe the bug**
Trying to delete a record registered with an UUID return a internal database error

**To Reproduce**
1. Create a datamodel with UUID
`type User {
  id: UUID! @unique
  name: String!
}
`
2. Create a record in the playground
`mutation {
  createUser(data: { name: "John" }) {
    id
    name
  }
}
`
`{
  "data": {
    "createUser": {
      "id": "8c3fde44-b096-43b2-82a2-e766800bfceb",
      "name": "John"
    }
  }
}`

3. Try to delete it
`mutation {
  deleteUser(where:{id:"8c3fde44-b096-43b2-82a2-e766800bfceb"}) {
    id
    name
  }
}`
`{
  "data": {
    "deleteUser": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:api:cjjxtfsij000m0839w20gmiit",
      "path": [
        "deleteUser"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "requestId": "local:api:cjjxtfsij000m0839w20gmiit"
    }
  ]
}
`

**Expected behavior**
Delete the record

**Screenshots**
Docker container log
![image](https://user-images.githubusercontent.com/30181675/43058546-958fc4fc-8e1e-11e8-9636-6bbdb4c84434.png)

**Versions:**
 - OS: Windows 10
 - ENV: prisma:1.13-beta and postgres images running on Docker 
 - CLI: prisma@1.13.0-beta.0

**Comment by mavilein** [comment]
The fix for this was merged a few days ago. So it is available in `1.13.4`.
