### ISSUE TITLE
Broken links in Docs

### ISSUE THREAD

**Issue by gijo-varghese** [prismagraphql/prisma#2821]
Please refer this doc: https://www.prisma.io/docs/tutorials/setup-prisma/connect-empty-db/postgres-aiy1jewith

In the 6th point, click on the link "reference documentation". It will be redirected to http://localhost:3000/docs/reference/prisma-servers-and-dbs/prisma-servers/docker-aira9zama5#configuration-with-docker-compose

Docs are full of bugs. This is one among the many

**Comment by divyenduz** [comment]
Thanks for raising the issue, we really appreciate it. We will act on this shortly.

**Comment by divyenduz** [comment]
Thanks for the feedback, Prisma is mature and is used in production by many organizations/users. 

However, I totally understand your point that it is not reflected by various parts of the docs. We are working on new docs that would be out soon and those will address all these issues. 

Thanks!

**Comment by marktani** [comment]
Thanks a lot for collecting these broken links, @gijo-varghese 🙏 
You might be interested in the upcoming new version of the documentation, which you can find here: https://docs-beta.prisma.io/.

**Comment by nikolasburk** [comment]
Thanks a lot for pointing this out @gijo-varghese and apologies for the inconvenience! 🙏  We're aware that our docs have been in a bad state over the past few months and have invested a lot into creating a versions that's better structured, more consistent and exhaustive. The new docs are currently in beta and you can find them [here](https://docs-beta.prisma.io/).

I also just fixed the broken link you're pointing out. We're working hard on creating helpful documentation for our developers! Please keep pointing us to issues like this in the future, this is a great help for us. Thanks! 🙏 👍

**Comment by gijo-varghese** [comment]
@nikolasburk pls take a look at the new docs from mobile. Its terrific!

**Comment by nikolasburk** [comment]
Sorry about the inconvenience again! We're aware that the beta docs have not been optimized for mobile yet. We're working on that and when released into production they'll be readable on mobile.

**Comment by gijo-varghese** [comment]
@nikolasburk the issues aren't fixed, you're saying it will be ready in docs in future (still beta) and the issue is closed. Why?

Dear @prisma team, these make us feel that Prisma is very immature and shouldn't be used for production. It's just a fancy tool!

Thanks anyway

**Comment by marktani** [comment]
Hey @gijo-varghese thanks so much for your perspective. I agree that broken links and the current mobile UI reflects poorly on Prisma itself. Hence we will put extra effort into improving this soon!

You can try out the docs on desktop for now. The new docs are the result of months-long iterations and cover much more topics than before, with an improved structure that supports you to find what you are looking for.  I am super excited about the new docs in general and I am curious to hear your perspective! Much of the recent improvements is based on user feedback and we will continue to listen to your feedback and put it into action.

Finally, I would like to challenge you to push Prisma to its limits from a technical perspective. I talk to many customers on a daily basis that run Prisma in production for months now. I am happy to help you find the best setup running Prisma in production as well. Hit me up on Slack (@nilan) if you want to take me up on that! 🙂 

Thanks for being a part of our community! 🙏

**Comment by gijo-varghese** [comment]
All links are broken in the new docs (beta)!

**Comment by nikolasburk** [comment]
Hi @gijo-varghese, I have tested a few links and it seems they're working. Can you please point me to the broken links you've found so I can fix them? Thanks!

**Comment by gijo-varghese** [comment]
@nikolasburk looks like they're fixed now

**Comment by nikolasburk** [comment]
I see, thanks a lot for letting us know 🙏
