### ISSUE TITLE
Support for JSONB and ARRAY formats

### ISSUE THREAD

**Issue by gijo-varghese** [prismagraphql/prisma#2822]
For our application **JSONB** and **ARRAY**, formats are very crucial. However, Prisma doesn't support these data types. Any plans for it?

**Comment by divyenduz** [comment]
For this feature no, but we will have a [public roadmap](https://github.com/prismagraphql/prisma/issues/2142) soon. 

About this specific issue, I will update the timeframe here as soon as I know.

Thanks!

**Comment by marktani** [comment]
Thanks a lot for raising this feature request, @gijo-varghese. I'll close it in favor of the more general one https://github.com/prismagraphql/prisma/issues/2466.
