### ISSUE TITLE
How to do complex migrations

### ISSUE THREAD

**Issue by gijo-varghese** [prismagraphql/prisma#2823]
I see Prisma can handle migrations. However, there aren't many docs regarding this.

How can I do complex migrations that involve sql queries?

For example I may need to convert `firstName` and `lastName` into `fullName`.

Another example can be like migrating data from one table to another table. How can these be done using Prisma?

**Comment by gijo-varghese** [comment]
@divyenduz Instead of searching in the issues, why can't you add a link to that issue in https://www.prisma.io/docs/reference/service-configuration/data-model/migrations-ao8viesh2r/ ??

Developers will look for the docs first, no issues. **One more reason not to use Prisma!**

**Comment by divyenduz** [comment]
@gijo-varghese : Thanks for the feedback, sounds good. I took a note and we will add it there. Generally, we have added issues in docs like this and we missed it. The docs are also editable from the same page. 

Thanks for the feedback again :)

**Comment by marktani** [comment]
Thanks for bringing this up, @gijo-varghese! As @divyenduz mentioned, let's use https://github.com/prismagraphql/prisma/issues/1263 for further discussions on migrations.

We have also created a dedicated channel to discuss migrations in [our Slack community](https://slack.prisma.io/), `#migrations`. Would love to see your input there as well!
