### ISSUE TITLE
orderBy: id_DESC / id_ASC returns an error

### ISSUE THREAD

**Issue by taikn** [prismagraphql/prisma#2837]
**Describe the bug**
Ordering by id ascending / descending is not working

**To Reproduce**
1. Clone the repo from here: https://github.com/taikn/prisma-sss-error
2. Install dependencies and launch server/playground
```bash
npm install
npm run dev
```
3. Run the following query in playground:
```graphql
query {
  users(where: { id:"cjgrv5uqa4vir0b59xhoflz35" } orderBy: id_DESC) {
    id
  }
}
```
4. Returns an error
```
{
  "error": {
    "errors": [
      {
        "message": null,
        "requestId": "eu1:api:cjk9rvfne0vho0b06po24kz6q"
      }
    ]
  }
}
```

**Expected behavior**
Expected to sort by ids

**Versions (please complete the following information):**
 - Prisma Server `1.13.0`

**Comment by goulderb** [comment]
+1, I am experiencing the same behavior.

**Comment by frankdugan3** [comment]
Same here!

**Comment by goulderb** [comment]
Hello @mavilein,

Thanks for the quick turnaround on this fix! I noticed that the changelog is not accurate (it references this ticket, but another commit entirely). Would it be possible for you to update the release notes to reflect this?

**Comment by sorenbs** [comment]
Updated the release description to point to the correct commit

**Comment by nolandg** [comment]
This is happening again. OrderBy works for every field except ID where it throws a monumentally uninformative graphql error. Prisma version 1.18.0, node 10.11.0, linux x64

prisma_1    | java.lang.IllegalArgumentException
prisma_1    | 	at com.prisma.api.connector.jdbc.database.OrderByClauseBuilder.orderByFields(OrderByClauseBuilder.scala:77)
prisma_1    | 	at com.prisma.api.connector.jdbc.database.OrderByClauseBuilder.orderByInternalWithAliases(OrderByClauseBuilder.scala:49)
prisma_1    | 	at com.prisma.api.connector.jdbc.database.OrderByClauseBuilder.orderByInternalWithAliases$(OrderByClauseBuilder.scala:45)
prisma_1    | 	at com.prisma.api.connector.jdbc.database.ModelQueryBuilder.orderByInternalWithAliases(QueryBuilders.scala:190)
prisma_1    | 	at com.prisma.api.connector.jdbc.database.OrderByClauseBuilder.orderByForModel(OrderByClauseBuilder.scala:16)
prisma_1    | 	at com.prisma.api.connector.jdbc.database.OrderByClauseBuilder.orderByForModel$(OrderByClauseBuilder.scala:11)
prisma_1    | 	at com.prisma.api.connector.jdbc.database.ModelQueryBuilder.orderByForModel(QueryBuilders.scala:190)
prisma_1    | 	at com.prisma.api.connector.jdbc.database.ModelQueryBuilder.query$lzycompute(QueryBuilders.scala:204)
prisma_1    | 	at com.prisma.api.connector.jdbc.database.ModelQueryBuilder.query(QueryBuilders.scala:201)
prisma_1    | 	at com.prisma.api.connector.jdbc.database.NodeManyQueries.getNodes(NodeManyQueries.scala:17)
prisma_1    | 	at com.prisma.api.connector.jdbc.database.NodeManyQueries.getNodes$(NodeManyQueries.scala:11)
prisma_1    | 	at com.prisma.api.connector.jdbc.database.JdbcActionsBuilder.getNodes(JdbcActionsBuilder.scala:21)
prisma_1    | 	at com.prisma.api.connector.jdbc.impl.JdbcDataResolver.getNodes(JdbcDataResolver.scala:35)
prisma_1    | 	at com.prisma.api.resolver.ManyModelDeferredResolver.resolve(ManyModelDeferredResolver.scala:19)
prisma_1    | 	at com.prisma.api.resolver.DeferredResolverProvider.$anonfun$resolve$1(DeferredResolverProvider.scala:65)
prisma_1    | 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
prisma_1    | 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:120)
prisma_1    | 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
prisma_1    | 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
prisma_1    | 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
prisma_1    | 	at com.prisma.api.resolver.DeferredResolverProvider.resolve(DeferredResolverProvider.scala:64)
prisma_1    | 	at sangria.execution.Resolver.sangria$execution$Resolver$$resolveDeferred(Resolver.scala:766)
prisma_1    | 	at sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$2(Resolver.scala:132)
prisma_1    | 	at sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$2$adapted(Resolver.scala:132)
prisma_1    | 	at scala.collection.Iterator.foreach(Iterator.scala:929)
prisma_1    | 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
prisma_1    | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
prisma_1    | 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
prisma_1    | 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
prisma_1    | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
prisma_1    | 	at sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$1(Resolver.scala:132)
prisma_1    | 	at sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$1$adapted(Resolver.scala:131)
prisma_1    | 	at scala.util.Success.foreach(Try.scala:249)
prisma_1    | 	at scala.concurrent.Future.$anonfun$foreach$1$adapted(Future.scala:224)
prisma_1    | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
prisma_1    | 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
prisma_1    | 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
prisma_1    | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
prisma_1    | 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
prisma_1    | 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
prisma_1    | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
prisma_1    | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
prisma_1    | 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
prisma_1    | 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
prisma_1    | 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
prisma_1    | 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
prisma_1    | null
prisma_1    | java.lang.NullPointerException
prisma_1    | 	at com.prisma.logging.LogDataWrites$.$anonfun$anyWrites$1(LogData.scala:24)
prisma_1    | 	at play.api.libs.json.Writes$$anon$6.writes(Writes.scala:143)
prisma_1    | 	at play.api.libs.json.DefaultWrites.$anonfun$mapWrites$2(Writes.scala:243)
prisma_1    | 	at scala.collection.MapLike$MappedValues.$anonfun$foreach$3(MapLike.scala:253)
prisma_1    | 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
prisma_1    | 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
prisma_1    | 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
prisma_1    | 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
prisma_1    | 	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:253)
prisma_1    | 	at scala.collection.MapLike.toSeq(MapLike.scala:335)
prisma_1    | 	at scala.collection.MapLike.toSeq$(MapLike.scala:330)
prisma_1    | 	at scala.collection.AbstractMap.toSeq(Map.scala:59)
prisma_1    | 	at play.api.libs.json.DefaultWrites.$anonfun$mapWrites$1(Writes.scala:243)
prisma_1    | 	at play.api.libs.json.OWrites$$anon$3.writes(Writes.scala:112)
prisma_1    | 	at play.api.libs.json.OWrites$$anon$3.writes(Writes.scala:111)
prisma_1    | 	at play.api.libs.json.PathWrites.$anonfun$nullable$2(JsConstraints.scala:185)
prisma_1    | 	at play.api.libs.json.OWrites$$anon$3.writes(Writes.scala:112)
prisma_1    | 	at play.api.libs.json.OWrites$MergedOWrites$.mergeIn(Writes.scala:76)
prisma_1    | 	at play.api.libs.json.OWrites$MergedOWrites$$anon$1.writeFields(Writes.scala:68)
prisma_1    | 	at play.api.libs.json.OWrites$MergedOWrites$$anon$1.writeFields(Writes.scala:64)
prisma_1    | 	at play.api.libs.json.OWrites$OWritesFromFields.writes(Writes.scala:96)
prisma_1    | 	at play.api.libs.json.OWrites$OWritesFromFields.writes$(Writes.scala:94)
prisma_1    | 	at play.api.libs.json.OWrites$MergedOWrites$$anon$1.writes(Writes.scala:64)
prisma_1    | 	at play.api.libs.json.OWrites$$anon$2.$anonfun$contramap$1(Writes.scala:107)
prisma_1    | 	at play.api.libs.json.OWrites$$anon$3.writes(Writes.scala:112)
prisma_1    | 	at play.api.libs.json.OWrites$$anon$3.writes(Writes.scala:111)
prisma_1    | 	at play.api.libs.json.Json$.toJson(Json.scala:189)
prisma_1    | 	at com.prisma.sangria.utils.ErrorHandler.com$prisma$sangria$utils$ErrorHandler$$logError(ErrorHandler.scala:65)
prisma_1    | 	at com.prisma.sangria.utils.ErrorHandler$$anonfun$handler$lzycompute$1.applyOrElse(ErrorHandler.scala:29)
prisma_1    | 	at com.prisma.sangria.utils.ErrorHandler$$anonfun$handler$lzycompute$1.applyOrElse(ErrorHandler.scala:21)
prisma_1    | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
prisma_1    | 	at sangria.execution.ResultResolver$ErrorRegistry.createErrorPaths(ResultResolver.scala:145)
prisma_1    | 	at sangria.execution.ResultResolver$ErrorRegistry.add(ResultResolver.scala:120)
prisma_1    | 	at sangria.execution.ResultResolver$ErrorRegistry$.apply(ResultResolver.scala:161)
prisma_1    | 	at sangria.execution.Resolver$$anonfun$$nestedInanonfun$resolveActionsPar$4$1.applyOrElse(Resolver.scala:615)
prisma_1    | 	at sangria.execution.Resolver$$anonfun$$nestedInanonfun$resolveActionsPar$4$1.applyOrElse(Resolver.scala:614)
prisma_1    | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
prisma_1    | 	at scala.util.Failure.recover(Try.scala:230)
prisma_1    | 	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:390)
prisma_1    | 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
prisma_1    | 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
prisma_1    | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
prisma_1    | 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
prisma_1    | 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
prisma_1    | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
prisma_1    | 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
prisma_1    | 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
prisma_1    | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
prisma_1    | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
prisma_1    | 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
prisma_1    | 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
prisma_1    | 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
prisma_1    | 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
prisma_1    | [Bugsnag - local / testing] Error report: com.bugsnag.Report@2c7522f1
prisma_1    | java.lang.NullPointerException
prisma_1    | 	at com.prisma.logging.LogDataWrites$.$anonfun$anyWrites$1(LogData.scala:24)
prisma_1    | 	at play.api.libs.json.Writes$$anon$6.writes(Writes.scala:143)
prisma_1    | 	at play.api.libs.json.DefaultWrites.$anonfun$mapWrites$2(Writes.scala:243)
prisma_1    | 	at scala.collection.MapLike$MappedValues.$anonfun$foreach$3(MapLike.scala:253)
prisma_1    | 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
prisma_1    | 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
prisma_1    | 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
prisma_1    | 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
prisma_1    | 	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:253)
prisma_1    | 	at scala.collection.MapLike.toSeq(MapLike.scala:335)
prisma_1    | 	at scala.collection.MapLike.toSeq$(MapLike.scala:330)
prisma_1    | 	at scala.collection.AbstractMap.toSeq(Map.scala:59)
prisma_1    | 	at play.api.libs.json.DefaultWrites.$anonfun$mapWrites$1(Writes.scala:243)
prisma_1    | 	at play.api.libs.json.OWrites$$anon$3.writes(Writes.scala:112)
prisma_1    | 	at play.api.libs.json.OWrites$$anon$3.writes(Writes.scala:111)
prisma_1    | 	at play.api.libs.json.PathWrites.$anonfun$nullable$2(JsConstraints.scala:185)
prisma_1    | 	at play.api.libs.json.OWrites$$anon$3.writes(Writes.scala:112)
prisma_1    | 	at play.api.libs.json.OWrites$MergedOWrites$.mergeIn(Writes.scala:76)
prisma_1    | 	at play.api.libs.json.OWrites$MergedOWrites$$anon$1.writeFields(Writes.scala:68)
prisma_1    | 	at play.api.libs.json.OWrites$MergedOWrites$$anon$1.writeFields(Writes.scala:64)
prisma_1    | 	at play.api.libs.json.OWrites$OWritesFromFields.writes(Writes.scala:96)
prisma_1    | 	at play.api.libs.json.OWrites$OWritesFromFields.writes$(Writes.scala:94)
prisma_1    | 	at play.api.libs.json.OWrites$MergedOWrites$$anon$1.writes(Writes.scala:64)
prisma_1    | 	at play.api.libs.json.OWrites$$anon$2.$anonfun$contramap$1(Writes.scala:107)
prisma_1    | 	at play.api.libs.json.OWrites$$anon$3.writes(Writes.scala:112)
prisma_1    | 	at play.api.libs.json.OWrites$$anon$3.writes(Writes.scala:111)
prisma_1    | 	at play.api.libs.json.Json$.toJson(Json.scala:189)
prisma_1    | 	at com.prisma.sangria.utils.ErrorHandler.com$prisma$sangria$utils$ErrorHandler$$logError(ErrorHandler.scala:65)
prisma_1    | 	at com.prisma.sangria.utils.ErrorHandler$$anonfun$handler$lzycompute$1.applyOrElse(ErrorHandler.scala:29)
prisma_1    | 	at com.prisma.sangria.utils.ErrorHandler$$anonfun$handler$lzycompute$1.applyOrElse(ErrorHandler.scala:21)
prisma_1    | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
prisma_1    | 	at sangria.execution.ResultResolver$ErrorRegistry.createErrorPaths(ResultResolver.scala:145)
prisma_1    | 	at sangria.execution.ResultResolver$ErrorRegistry.add(ResultResolver.scala:120)
prisma_1    | 	at sangria.execution.ResultResolver$ErrorRegistry$.apply(ResultResolver.scala:161)
prisma_1    | 	at sangria.execution.Resolver$$anonfun$$nestedInanonfun$resolveActionsPar$4$1.applyOrElse(Resolver.scala:615)
prisma_1    | 	at sangria.execution.Resolver$$anonfun$$nestedInanonfun$resolveActionsPar$4$1.applyOrElse(Resolver.scala:614)
prisma_1    | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
prisma_1    | 	at scala.util.Failure.recover(Try.scala:230)
prisma_1    | 	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:390)
prisma_1    | 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
prisma_1    | 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
prisma_1    | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
prisma_1    | 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
prisma_1    | 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
prisma_1    | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
prisma_1    | 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
prisma_1    | 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
prisma_1    | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
prisma_1    | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
prisma_1    | 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
prisma_1    | 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
prisma_1    | 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
prisma_1    | 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
