### ISSUE TITLE
Add `--endpoint` option to `prisma init`

### ISSUE THREAD

**Issue by nikolasburk** [prismagraphql/prisma#2838]
When passing the `--endpoint` option to `prisma init`, the CLI should:

- Create `datamodel.graphql` with the default `User` type:

    ```graphql
    type User {
      id: ID! @unique
      name: String!
    }
    ```
- Create prisma.yml with the `endpoint` specified as the value of the `--endpoint` option and `datamodel` pointing to `datamodel.graphql`

For example:

```bash
prisma init --endpoint http://localhost:4466/myservice/dev
```

Creates above specified `datamodel.graphql` and the following prisma.yml:

```yml
endpoint: http://localhost:4466/myservice/dev
datamodel: datamodel.graphql
```

**Comment by abhiaiyer91** [comment]
@nikolasburk Will this still prompt for management secrets?

**Comment by divyenduz** [comment]
The current assumption is that `--endpoint` will be a separate code path that does not ask for other details and just writes the files. 

@nikolasburk : Can you please clarify?

**Comment by nikolasburk** [comment]
@divyenduz that's correct! There's no need for the interactive wizard because the ultimate goal of the wizard is to figure out the Prisma server to which the new service should be deployed. If the `endpoint` is passed to the command, the wizard is rendered obsolete.
