### ISSUE TITLE
Getting error "Could not connect to cluster prisma-us1 with host https://us1.prisma.sh ..."

### ISSUE THREAD

**Issue by kvo1** [prismagraphql/prisma#2841]
**Describe the bug**

Getting the error:
"Could not connect to cluster prisma-us1 with host https://us1.prisma.sh. Did you provide the right port?"

This error shows on the console when I run `yarn start`.

My Prisma services work for months until Jul 29. It started showing the error on Jul 29. I tried starting the service again on Jul 30 and it's gone. But, it happens again today morning (Jul 31).

**To Reproduce**
1. Run `yarn start`
2. See error

**Expected behavior**
Prisma service must be started as usual.

**Screenshots**

![prisma-error](https://user-images.githubusercontent.com/40276915/43479569-ef38b45a-94bd-11e8-8582-3973d5786c10.PNG)

**Versions:**
 - OS: `Windows 10`
 - `prisma` CLI: `prisma/1.12.0`

**Comment by IvanVolkov-12devs** [comment]
The same problem!
Starts from yesterday (31 July)
I can manage for existing Data from - https://app.prisma.io/ but - "Yarn Start" return me this error...

**Comment by divyenduz** [comment]
@kvo1 , @IvanVolkov-12devs : Are you running it behind a proxy?

**Comment by kvo1** [comment]
@divyenduz Nope, mine isn't behind any proxies. It's still an issue now.

**Comment by IvanVolkov-12devs** [comment]
@kvo1 I also don't use proxy.
I had to run it locally - https://www.prisma.io/docs/tutorials/setup-prisma/create-new-db/mysql-gui4peul2u/ in conjunction with https://github.com/somus/prisma-admin that i found

**Comment by marktani** [comment]
The demo server runs on `1.13.3`, can you reproduce this with the same CLI version?

**Comment by kvo1** [comment]
@marktani That was my mistake. I have my nodejs project setup with the prisma (v1.5) installed locally,.. and prisma (v.1.13) installed globally. 

@IvanVolkov-12devs Double check if you have local prisma installed in your project.
