### ISSUE TITLE
Additional information on using updateManyXs

### ISSUE THREAD

**Issue by yantakus** [prismagraphql/prisma#2845]
I tried following `updateManyXs` migration described here: https://www.prisma.io/docs/1.7/reference/service-configuration/data-modelling-(sdl)-eiroozae8u/ (BTW right now the website is not working).

So my mutation looks like this:

```
mutation {
  updateManyUsers(where: {login: null}, data: {login: ""})
}
```

But all I get is this error message without any useful debug info:

```
{
  "errors": [
    {
      "message": "Response not successful: Received status code 400",
      "locations": [
        "Error: Response not successful: Received status code 400\n    at throwServerError (http://localhost:3001/_next/-/page/index.js:4581:17)\n    at http://localhost:3001/_next/-/page/index.js:4606:13"
      ]
    }
  ]
}
```

My setup is the following: https://github.com/graphql-boilerplates/node-graphql-server/tree/master/advanced (created with the following command: `npx graphql-cli create myapp --boilerplate node-advanced`).

I tried running the above mutation from both Playground at http://localhost:4000 and apollo developer tools with no success. When I run these mutations, there's no logs about incoming mutation in the terminal window where I run the server. Does it mean these mutations just don't come through and fail somewhere before?

I searched for `updateManyUsers` and it does exist in `server/src/generated/prisma.graphql`:

```
updateManyUsers(data: UserUpdateInput!, where: UserWhereInput): BatchPayload!
```

But I can't understand why it doesn't work. Is there any way to get additional debug information?

**Comment by marktani** [comment]
That is not a valid mutation.

This is a valid mutation:

```graphql
mutation {
  updateManyUsers(where: {login: null}, data: {login: ""}) {
    __typename
  }
}
```

**Comment by yantakus** [comment]
@marktani thanks. Thanks for the tip, it would be very useful to have this info in the docs.

Also, is there a way to get additional debug information from the server when there's error? I mean getting something more useful than just `Response not successful: Received status code 400`?

**Comment by marktani** [comment]
You can enable debug output from your server.
This will print raw GraphQL operations to `stdout`.

You can take these raw operations and send them directly against the Prisma API (not against your application server).

In this case you would have received an error message that the GraphQL operation is invalid.

If you think this can be improved, I'd love to see a feature request [here](https://github.com/prismagraphql/graphql-yoga).

We will consider how to better cover this in the docs, thanks for the suggestion! 🙌
