### ISSUE TITLE
Field "OR" is not defined by type UserWhereUniqueInput

### ISSUE THREAD

**Issue by jimmyjamieson** [prismagraphql/prisma#2874]
**Describe the bug**
Trying to do 
```
const user = await ctx.db.query.user({
        where: {  OR: [
            { facebookUserId: id },
            { email: email },
          ], },
 });
```

causes prisma to error with:

```
Variable "$_v0_where" got invalid value {"OR":[{"facebookUserId":"xxxxxx"},{"email":"xxxxxx@gmail.com"}]}; Field "OR" is not defined by type UserWhereUniqueInput
```

**To Reproduce**

Create a User schema, and make sure WHERE fields use @unique 

```
type User {
  id: ID! @unique
  username: String! @unique
  email: String! @unique
  password: String!
  name: String!
  facebookUserId: String @unique
  googleUserId: String @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  posts: [Post!]!
  listings: [Listing!]! @relation(name: "ListingsByUser" onDelete: CASCADE)
}
```

Try calling within a Mutation
```
async facebookLogin(parent, { appId, token, redirectUrl }, ctx) {

    const facebookSecret='XXXXXXXX';

    const fields = `id,name,email,first_name,last_name,birthday,locale,gender,picture`;
    const accessEndpoint = `https://graph.facebook.com/v3.1/oauth/access_token?client_id=${appId}&redirect_uri=${redirectUrl}&client_secret=${facebookSecret}&code=${token}`;
    const userEndpoint = `https://graph.facebook.com/v3.1/me?fields=${fields}`;

    try {
      const getAccessToken = await axios.get(accessEndpoint);
      const { access_token } = await getAccessToken.data;
      const data = await axios.get(`${userEndpoint}&access_token=${access_token}`);

      console.log('$$$ DATA', data.data);

      const { id, name, email } = await data.data;

      const user = await ctx.db.query.user({
        where: {  OR: [
            { facebookUserId: id },
            { email: email },
          ], },
      });

     ...the rest
```

**Expected behavior**
It should return a user based on the facebookUserId, or email address

**Versions (please complete the following information):**
 - OS: Windows 10
 - `prisma` CLI: prisma/1.13.4 (windows-x64) node-v8.11.1
 - Prisma Server: prismagraphql/prisma:1.8
 - `graphql-cli`, `prisma-binding`, `graphql-yoga`

**Comment by jimmyjamieson** [comment]
I just updated to latest prismagraphql/prisma:1.13, same error

**Comment by marktani** [comment]
The `where` of the `user` query only exposes unique fields.

Instead, you can either use the `users` query, or send two `user` queries - one using the `facebookId` and one using the `email` unique filter.

**Comment by jimmyjamieson** [comment]
Ah ok, that makes sense. I'll give it a try, thanks.

**Comment by sahildeliwala** [comment]
I'm getting this error now.
OR in where is not working
I'm following this tutorial: https://www.howtographql.com/graphql-js/8-filtering-pagination-and-sorting/
However I'm using latest prisma install locally in docker container with MongoDB

![2019-02-15_1327](https://user-images.githubusercontent.com/10909011/52842598-91223580-3125-11e9-8c61-93af4e3f3552.png)
