### ISSUE TITLE
Relations between tables

### ISSUE THREAD

**Issue by truesik** [prismagraphql/prisma#2875]
Is there any way to get "direct" relation between tables in prisma datamodel without creating additional link table?

For example, I have two tables:

```
create or replace table data_type
(
  id          bigint       not null
  description varchar(200),
  name        varchar(100) not null
);

create or replace table property
(
  id                    bigint       not null
  description           varchar(500),
  name                  varchar(100) not null,
  data_type             bigint       not null
);
```

**Comment by mavilein** [comment]
Hey @truesik ,

thanks for reaching out. This is possible with out support for existing databases (currently Postgres only). I suggest the following:
1. Create this schema in a Postgres database. Make sure to also add foreign key constraint on the `data_type` column in the `property` table.
2. Run `prisma init` command to generate the data model for this schema. You must select the `Use existing database` in the first step.

This will generate a datamodel for you and docker compose file that configures a Prisma server with support for existing databases. You will see that `migrations` is set to false in the server config. You can read more about this setting here: https://docs-beta.prisma.io/1.13/operate-prisma-server/database-connector-MYSQL-jgfs/

**Comment by mavilein** [comment]
I closing this for now. Feel free to reopen!
