### ISSUE TITLE
Link in README does not work

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2889]
The README in this repo contains this line:
```
- [**Build a GraphQL server (recommended)**](https://www.prisma.io/docs/tutorials/-ohdaiyoo6c)
```

Clicking on this link leads to a blank page with this error message:

![image](https://user-images.githubusercontent.com/1780597/43828143-f2b18d2a-9afb-11e8-8986-182f53fb77ba.png)

**Comment by captDaylight** [comment]
I just tried clicking on the link on github, works for me. Is there another context this isn't working in?

**Comment by marktani** [comment]
I can confirm, now the link works for me as well. This was probably due to a failed CI build.
Thanks for chiming in, @captDaylight!
