### ISSUE TITLE
Prisma Cloud Error: "GraphQL error: Cannot return null for non-nullable field CreateField.isList."

### ISSUE THREAD

**Issue by liamdanielduffy** [prismagraphql/prisma#2901]
**Describe the bug**

When viewing a data type in the data browser on Prisma Cloud, I see 

**To Reproduce**
Setup a Prisma Cloud service, then load the data browser for a type. 

**Expected behavior**

I would expect not to see internal Prisma errors thrown in Prisma Cloud

**Screenshots**

<img width="586" alt="screen shot 2018-08-09 at 3 15 33 pm" src="https://user-images.githubusercontent.com/7659261/43891532-2c3d3440-9be7-11e8-8623-4c03b96808fe.png">

**Versions (please complete the following information):**

Prisma server is running 1.14 beta-1

**Additional context**

**Comment by marktani** [comment]
This is not a generally reproducible bug, but an error specific to your service. Could you please reach out to support@prisma.io so we can look into this problem to find a solution for you and potentially document the underlying bug? 🙂I'm closing this issue for now.
