### ISSUE TITLE
Accept naked URLs in "Connect Server" or specify the http prefix requirement

### ISSUE THREAD

**Issue by jhalborg** [prismagraphql/prisma#2902]
**Describe the bug**
I think it would prevent a lot of wasted time and questions if the "Connect to Server" interface either accepted "naked" URLs (without `http(s)` / `www` in front) or specified that it was required. 

**To Reproduce**
1. Go to Prisma Console
2. Go to servers
3. Press add server
4. Select "connect to existing"
5. Input server URL without `https://`

![image](https://user-images.githubusercontent.com/6643672/43894943-f6a0e01a-9bd3-11e8-8bbb-b24ffe44ab16.png)

**Expected behavior**
Expected connection to happen, or error saying that it must be a full URL, i.e. "Please include https://"

**Comment by marktani** [comment]
Issue moved to [prismagraphql/prisma-cloud-feedback #198](https://github.com/prismagraphql/prisma-cloud-feedback/issues/198) via [**ZenHub**](https://www.zenhub.com/)
