### ISSUE TITLE
For input string: "null"

### ISSUE THREAD

**Issue by kurt-o-sys** [prismagraphql/prisma#2910]
**Describe the bug**
I was changing my graphql model and at a certain point, it failed to deploy. The deployment didn't succeed.
So I reverted my changes, and tried to deploy again, and I'm always getting the same error:
```
There are issues with the new service definition:

  Global
    ✖ For input string: "null"
```
When I deploy these changes on another environment, there's no problem. 
It seemed that it was due to the data, so I did a data reset on the failing environment and I tried to deploy again. Still the same error. 

In short: I can't do anything anymore on that failing environment, everything I try results in the same error (see above)

**To Reproduce**
1. run graphcool reset
2. deploy a new db model that works on another environment
3. see it doesn't deploy on this failing environment

**Expected behavior**
successful deployment, certainly after resetting the data

**Versions (please complete the following information):**
```
 cat /etc/lsb-release    
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18
DISTRIB_CODENAME=sarah
DISTRIB_DESCRIPTION="Linux Mint 18 Sarah"
$ npm view graphcool version
...
0.11.6
...
```

**Comment by marktani** [comment]
Issue moved to [prismagraphql/graphcool-framework #553](https://github.com/prismagraphql/graphcool-framework/issues/553) via [**ZenHub**](https://www.zenhub.com/)
