### ISSUE TITLE
Prisma docs website returning HTTP error 508

### ISSUE THREAD

**Issue by stefanfuchs** [prismagraphql/prisma#2911]
Hi, I'm trying to open the documentation from the website, but it shows an HTTP error.
https://www.prisma.io/docs/
Could you take a look please?
Thanks

**Comment by marktani** [comment]
Thanks, we're looking into this. It seems to be an issue with our CDN, affecting a small amount of users.

Until we resolved this, you can refer to the new version of the docs [here](https://docs-beta.prisma.io/) or read the old version of the docs [here](https://github.com/prismagraphql/prisma/tree/master/docs).

**Comment by stefanfuchs** [comment]
Thank you. I will take a look at those links.
