### ISSUE TITLE
Relation onDelete : "violate the required relation"

### ISSUE THREAD

**Issue by Illuday** [prismagraphql/prisma#2914]
Hi, when I try to delete anode A or B, it returns me an error. I saw that the onDelete: SET_NULL is not required, but I think this is an issue. Have you an idea about this ?

**MODEL :**
```
type Article {
    user: User! @relation(name: "MyArticles", onDelete: SET_NULL)
}

type User {
    article: [Article !]! @relation(name: "MyArticles", onDelete: SET_NULL)
}
```

**MUTATION :**
```
deleteArticle(id: ID!): Article!

return ctx.db.mutation.deleteArticle({ where: { id } });
```

*The change you are trying to make would violate the required relation 'MyArticles' between Article and User*

**Comment by marktani** [comment]
Have you tried to do `onDelete: CASCADE` instead?
Here is more information about the behaviour of cascading deletes: https://www.prisma.io/forum/t/help-with-cascading-deletes/3878/2?u=nilan.

**Comment by Illuday** [comment]
Nop, the thing is that I don't want to delete anything.

**Comment by marktani** [comment]
Can you share a reproduction according to the [bug report template](https://github.com/prismagraphql/prisma/issues/new?template=bug_report.md)? This looks like unexpected behaviour.

**Comment by Illuday** [comment]
Well, my bad, I had a "not null" condition on my relationnal node. See #1795
