### ISSUE TITLE
Generate documentation for API

### ISSUE THREAD

**Issue by danmkent** [prismagraphql/prisma#306]
It would be great if the graph.cool web interface had a view that showed documentation for the generated graphql API, like that generated by https://github.com/mhallin/graphql-docs or https://github.com/2fd/graphdoc

This would be a bit like the existing graphiql docs tab but formatted to fill the whole window like the graph view does. It would also be really useful if this view could be access from its own URL so that it could be left open in its own browser tab as a reference when coding against the generated API.

**Comment by kbrandwijk** [comment]
Just use the service the nice competitor is offering: Open your browser to: 
https://graphql-docs.com/docs/?graphqlUrl=https://api.graph.cool/simple/v1/__PROJECTID__

and you've got yourself your API docs :smile:

**Comment by sedubois** [comment]
It could be quite nice to use something like Slate (https://github.com/lord/slate) to have an experience similar to the Stripe documentation but with Graphcool/GraphQL.

**Comment by marktani** [comment]
The new GraphQL Playground comes with a great docs experience - check it out here: https://blog.graph.cool/introducing-graphql-playground-f1e0a018f05d

**Comment by eruby94** [comment]
The new playground docs are great, but are limited when developing on only a single laptop screen. Though I generally do my dev with 1+ additional monitors, not everyone will have that luxury. It would be very helpful to have the docs (presented exactly as they are), but available via a separate console tab.

<img width="288" alt="screen shot 2017-10-01 at 10 56 05 am" src="https://user-images.githubusercontent.com/12565404/31055847-2c3a3600-a697-11e7-916c-8cf8bff8aae2.png">

Consider the above screenshot: I can see all of my primary navigation in the console, but toward the bottom, I am presented with two buttons: Endpoints, and Docs. I click on endpoints, and as I would think, the endpoints are presented, specific to my project. On the contrary, when I click on docs, it takes me to the graphcool docs, not my project docs (which was slightly confusing at first).

I love having easy accessibility to see the graphcool docs with a button click from the console, but it would seem more logical to have this particular placement link to project-specific docs, presented in  such a way that takes up the console view entirely.

<img width="1439" alt="screen shot 2017-10-01 at 11 00 24 am" src="https://user-images.githubusercontent.com/12565404/31055887-c8a301b6-a697-11e7-917d-ccb84957c329.png">

TL,DR; - It would be nice to separate the Docs portion, as shown above, into a full screen view.

**Comment by kbrandwijk** [comment]
It would be nice if you could 'detach' the docs, making them open in a new window, so you could put that on your other display (similar to how you can 'detach' the dev tools in Chrome)

**Comment by marktani** [comment]
Issue moved to [prismagraphql/prisma-cloud-feedback #153](https://github.com/prismagraphql/prisma-cloud-feedback/issues/153) via [**ZenHub**](https://www.zenhub.com/)

**Comment by katemicse** [comment]
how can i take that documentation pages? i need to add api documentation to my production project- should i use that one generated in graphql playground? 
Is it normal to enable graphql playground on production site?

How to deal with api cals made in production? i mean if theres is api for changing something how to handle them and prevent real productions database changes?
