### ISSUE TITLE
API doesn't handle float values correctly

### ISSUE THREAD

**Issue by schickling** [prismagraphql/prisma#404]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Sunday Jul 09, 2017 at 00:29 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/174_

----

**What is the current behavior?**
When an integer is used as input value for a float field, this should be coerced to a float by adding and empty fractional part. This does not happen.

When a float field is queried, the result should also be coerced to a float. Currently, an integer value is returned.

Spec here: https://facebook.github.io/graphql/#sec-Float

**What is the expected behavior?**
Handle float values according to spec.

**Comment by marktani** [comment]
For faster reproduction:

```graphql
type Item implements Node {
  float: Float!
  id: ID! @isUnique
}
```

```graphql
mutation {
  createItem(float: 1) {
    float
  }
}
```

returns

```json
{
  "data": {
    "createItem": {
      "float": 1
    }
  }
}
```

but should return

```json
{
  "data": {
    "createItem": {
      "float": 1.0
    }
  }
}
```

as per this section:

> When expected as an input type, both integer and float input values are accepted. Integer input values are coerced to Float by adding an empty fractional part, for example 1.0 for the integer input value 1.
