### ISSUE TITLE
Weird wording in error message for invalid floats

### ISSUE THREAD

**Issue by schickling** [prismagraphql/prisma#416]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Thursday Jul 27, 2017 at 08:29 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/208_

----

**What is the current behavior?**

Trying to store a float value with many (~15) digits behind the decimal point results in a weird error message.

**Reproduction**

```graphql
type A implements Node {
  f: Float
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
}
```

```graphql
mutation {
  createA(f: 1.23456789012345678) {
    id
  }
}
```

```json
{
  "data": null,
  "errors": [
    {
      "message": "Argument 'f' expected type 'Float' but got: 1.23456789012345678. Reason: Float or Int value is too bit to fit in double (line 2, column 14):\n  createA(f: 1.23456789012345678) {\n             ^",
      "locations": [
        {
          "line": 2,
          "column": 14
        }
      ]
    }
  ]
}
```

**What is the expected behavior?**

A better wording than `Reason: Float or Int value is too bit to fit in double` should be presented to the user.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Thursday Jul 27, 2017 at 19:15 GMT_

----

This is according to specification. All numbers in Javascripts are 64-bit doubles according to IEEE 754. This means they have 15.95 (=16) decimal places.

This works:
```
mutation {
  createA(f: 0.1234567890123456) {
    id
  }
}
```
As the first `0` is ignored, you have 16 decimals left.
```
mutation {
  createA(f: 10.12345678901234) {
    id
  }
}
```
This also works, with a total of 16 decimals.

Sources: https://en.wikipedia.org/wiki/Double-precision_floating-point_format and https://en.wikipedia.org/wiki/IEEE_754

**Comment by marktani** [comment]
Right. I adjusted the expected behaviour in my original post.

**Comment by marktani** [comment]
The error message originates from Sangria: https://github.com/sangria-graphql/sangria/commit/a63472ff375953ea5121b6927470692d613ba67b.

**Comment by marktani** [comment]
As we use Sangria 1.3.3, this should be fixed.
