### ISSUE TITLE
Add apply/cancel functionality when editing a record in databrowser

### ISSUE THREAD

**Issue by schickling** [prismagraphql/prisma#490]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Sunday Jun 11, 2017 at 17:32 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/49_

----

Now, all changes are applied immediately, which is error sensitive.

**Comment by marktani** [comment]
This feedback has been incorporated into the editing workflow of Prisma console.
