### ISSUE TITLE
Improve UI for making relations between nodes in "data" GUI

### ISSUE THREAD

**Issue by schickling** [prismagraphql/prisma#491]
<a href="https://github.com/JensMadsen"><img src="https://avatars1.githubusercontent.com/u/6726111?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JensMadsen](https://github.com/JensMadsen)**
_Wednesday Jun 14, 2017 at 10:03 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/50_

----

It took me some time to figure out how to make a relation between two nodes. Especially when I was adding self-relations. A simple improvement would be to add a text saying something like: "Select node (row) for relation to node x".

**Comment by marktani** [comment]
Closing due to being outdated.
