### ISSUE TITLE
Proposing for the re-designing of the data form on graphcool console

### ISSUE THREAD

**Issue by schickling** [prismagraphql/prisma#495]
<a href="https://github.com/Musbell"><img src="https://avatars3.githubusercontent.com/u/4477954?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Musbell](https://github.com/Musbell)**
_Friday Jun 23, 2017 at 16:20 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/54_

----

I am proposing if the data form on the console could be in a form view format in which i think it will be much more comfortable to be scrolling vertically instead of horizontally when one has a long data field.  
Like this:  http://evilrockhopper.com/wp-content/uploads/2009/10/picture-1.png?

**Comment by marktani** [comment]
This feedback has been incorporated into the editing workflow of Prisma Console.
