### ISSUE TITLE
Resolution for createdAt time is insufficient

### ISSUE THREAD

**Issue by kbrandwijk** [prismagraphql/prisma#599]
If you create a number of nodes in quick succession (for example, in the same mutation), they all end up with the same `createdAt` time. Although the display value is: hh:mm:ss.sss, the resolution is actually 1 second, because the '.sss' part is always .000.

This causes blocking problems with ordering (for example: https://www.graph.cool/forum/t/the-createdat-are-completely-same/1024)

**Comment by do4gr** [comment]
A fix is available in stable now.
