### ISSUE TITLE
Prompt user to upgrade CLI if it's outdated

### ISSUE THREAD

**Issue by schickling** [prismagraphql/prisma#611]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Wednesday May 17, 2017 at 10:28 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/79_

----

We also should think about semantic versioning etc

**Comment by marktani** [comment]
This now happens.
