### ISSUE TITLE
Change local to dedicated

### ISSUE THREAD

**Issue by rwatts3** [prismagraphql/prisma#803]
With the new features of @next tag I noticed that the term local is being used to describe a local docker cluster. If the end game for this direction is to allow the user to push their own cluster I believe the term local should be switched to dedicated, as you're running a dedicated instance of a graphcool setup. Not necessarily a local instance. I could have a local development instance, and my own instance in the cloud on aws or digitalocean for that matter. 

Also can the graphcool console interface be available as an option or service for users running on the local environment. I like the ability to change my schema and make changes to the schema within the GUI as well as the ability to change the schema via source.

**Comment by marktani** [comment]
Thanks for your feedback! As far as I know `local` does not have any special meaning in Prisma anymore.
