### ISSUE TITLE
Add command-line argument to connect local docker image to specific docker network

### ISSUE THREAD

**Issue by kbrandwijk** [prismagraphql/prisma#899]
**What feature are you missing?**
The ability to connect the local docker instance to an existing docker network is useful when running multiple docker images. For example, I'm running aws-sam-local to get a local AWS API gateway for all my functions, which supports specifying a docker network. If I could specify the same network for the local Graphcool docker instance, it's easier to connect them.
This feature will also be useful when adding a second local docker instance for the new Graphcool API Gateway.

**How could this feature look like in detail? Tradeoffs?**
A command line argument to the `graphcool local` command like `--docker-network my custom network`. See https://github.com/awslabs/aws-sam-local#connecting-to-docker-network for an example.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).

**Comment by akoenig** [comment]
@marktani I also stumbled upon this and think that this is also a feature for the Prisma CLI. Imagine a scenario in which you have your Prisma service, your front-facing GraphQL API and additional services you want to connect to the local Prisma cluster network. Think of an endpoint that gets triggered by a [Server-side subscription](https://www.prismagraphql.com/docs/reference/server_side-subscriptions/overview-to1ahf0ob6). It is likely that this endpoint also runs in a local container, but if not configured in an own separated network. A workaround for the moment is to run the endpoint container in the `local_prisma` network as well, but that makes it pretty error-prone. Making the network configurable via `prisma local start --network mynetworkname` would be a nice addition.

**Comment by marktani** [comment]
This is not valid anymore since the deprecation of the local commands.
